### ISSUE TITLE
Sozi on Steroids -- making the frame making process faster

### ISSUE THREAD

**Issue by assela** [senshu/Sozi#106]
I have successfully used sozi to make two two large presentations. I can confirm that it is an excellent tool ready for prime-time!

One issue I had using sozi was that I had to wait a few tens of seconds each time when I add a new sozi frame to my presntation in Inkscape. Soon I got fedup with this and wrote a small script that can speed up the task for me. 

How it works:
1.  Make a frame in Inkscape and give it a simple id (Right Click->Object Properties). Say you named it "new_frame". Then add it to sozi. 
2. Copy this frame ("new_frame") to make a number of other frames where you need to focus on. 
3. Save the svg. Exit Inkscape and run the script with SVG file and "new_frame" as arguments. 
4. In the resulting svg file (<original_name>.svg_.svg)  all the new frames are added to Sozi. If you want open it in Inskscape and fine-tune the sozi names of those frames. 

At the moment it is just a plain hack (http://assela.pathirana.net/sozi). But if anyone finds it useful please feel free to use. 

My question is: Can someone think of adding such a feature to Sozi itself (adding multiple frames once)?

Assela

At the moment it is a hack (http://assela.pathirana.net/sozi)

**Comment by senshu** [comment]
Sozi 13 is no longer developed. I am now closing all issues related to Sozi 13.
Please try Sozi 15 and open a new issue if you think that your problem still deserves to be addressed.
