### ISSUE TITLE
Hiding frame numbers

### ISSUE THREAD

**Issue by sadata** [senshu/Sozi#117]
12.04 seems to have introduced a circular frame number that displays in the top left of the frame.  I didn't see anything about this in the release notes, nor how to disable it.  I found that it can be hidden by modifying the sozi-framenumber class in the CSS as shown below.  Note that setting 'display: none' results in the entire frame being hidden. 

#sozi-framenumber circle {
   stroke-width: 0;
   fill: none;
}

#sozi-framenumber text {
   stroke-width: 0;
   fill: none;
}

**Comment by senshu** [comment]
An option to hide frame numbers has been added to Sozi 15
