### ISSUE TITLE
version compatibility issue

### ISSUE THREAD

**Issue by alxsal** [senshu/Sozi#124]
Computer A : sozi 12.05-1ubuntu0~sunab~precise3 (ppa install) / Inkscape 0.48.3.1-1ubuntu1 / Ubuntu 12.04.
Computer B : sozi 12.05-1ubuntu0~sunab~natty3 (ppa install) / Inkscape 0.48.1-2ubuntu2 / Ubuntu 11.04

I created a sozi presentation on computer A.
Then moved to computer B, continued to work, added videos, no problem.
Then came back to computer A, tried to add a frame or another video
-> got the error msg "Document has been created using a higher version of Sozi. Please upgrade the Inkscape plugin." 
Used Sozi extras > Upgrade on computer A, but the problem remains...

**Comment by eldelacajita** [comment]
Exact same problem here. The workaround by @alxsal did work, thanks!
