### ISSUE TITLE
Show Frame Title on Canvas

### ISSUE THREAD

**Issue by tvld** [senshu/Sozi#162]
It is hard to see what frame belongs to which Rectangle. Is there any way to show the title in the Canvas?
![Screenshot from 2012-12-13 13:49:52](https://f.cloud.github.com/assets/986182/10547/b14bd054-4523-11e2-986f-f5cd941c3338.png)

**Comment by senshu** [comment]
Sozi 13 is no longer developed. I am now closing all issues related to Sozi 13.
Please try Sozi 15 and open a new issue if you think that your problem still deserves to be addressed.
