### ISSUE TITLE
Use Object Properties Title for Frame name

### ISSUE THREAD

**Issue by tvld** [senshu/Sozi#163]
Can we use Object Properties for the Frame name?  Introducing new name structure seems not re
![Screenshot from 2012-12-13 13:52:08](https://f.cloud.github.com/assets/986182/10554/169cef74-4524-11e2-82b9-e95ec0dde768.png)
quired?

**Comment by senshu** [comment]
Sozi 13 is no longer developed. I am now closing all issues related to Sozi 13.
Please try Sozi 15 and open a new issue if you think that your problem still deserves to be addressed.
