### ISSUE TITLE
Fade in/out

### ISSUE THREAD

**Issue by roggan87** [senshu/Sozi#175]
I found sozi today, and I've played around with it. Gotta say I love it already!

One feature I think would be nice is to be able to fade in/out a layer as the transition. Fade in would be done like so:

1. Hide the particular layer (0ms)
2. Resize and rotate according to the frame while fading in (x ms)

**Comment by senshu** [comment]
Commit 974847277e54f805f19dc81d3ce4b7e2af582431 adds the following feature: in a given frame of your presentation, you can modify the opacity of each layer. For instance, you can choose to make one layer fully transparent while another is fully opaque. Transitions between frames where a layer has different opacities will produce a fade-in or fade-out effect, unless you choose one of the "step" timing functions.

This feature is avaliable in [Sozi 15.04.242301](https://drive.google.com/open?id=0ByRUreHgekjMfjFOWjJIbFZfVFRVcVRRRDdJNzFMcjd6eUM1M005Qm9fam9RcDhvZmZORG8&authuser=0)
