### ISSUE TITLE
Preview presentation

### ISSUE THREAD

**Issue by roggan87** [senshu/Sozi#176]
Right now, to preview the effects applied, I must close the sozi window, save the document, open it in firefox and run, right?

How about adding a "preview button" next to ok and cancel? Clicking preview would open up a minimal SoziBrowser (using WebKit), that would display the temporary presentation in fullscreen. Close by pressing [Esc] or [q].

Alternatively, the preview area could be placed next to the other options in the sozi dialog, so changes are updated in real time, and previewing is as easy as click and watch.

I've started to implement this. The SoziBrowser is done, and it's working with my presentations so far. I have yet to integrate it into the sozi dialog. Any feedback is welcome.

**Comment by senshu** [comment]
Sozi 13 is no longer developed. I am now closing all issues related to Sozi 13.
Please try Sozi 15 and open a new issue if you think that your problem still deserves to be addressed.
