### ISSUE TITLE
Show Frame Sequence number on Canvas

### ISSUE THREAD

**Issue by tvld** [senshu/Sozi#182]
With presentations with more than 40 frames or so, when reordering frames it is not easy to keep track of the flow.

Can we display, maybe toggle, a label next to the frame with the sequence number ? 

For example, we could do this by selecting a text object in the Frame, just like we now select the frame or the transition path:

   "Fill with sequence nr: " [text object]
    checkbox to hide yes/no

Side benefit: this number is then actually a page number in the presentation. For this to appear they would not check the hide checkbox.

See also Issue 162

**Comment by senshu** [comment]
Sozi 13 is no longer developed. I am now closing all issues related to Sozi 13.
Please try Sozi 15 and open a new issue if you think that your problem still deserves to be addressed.
