### ISSUE TITLE
Show Transistion Path Label

### ISSUE THREAD

**Issue by tvld** [senshu/Sozi#186]
Trying to have 20 Transition Paths in one Sozi... wow....

Just as with Frames... it would be great to show next to a Transition Path the Frame Sequence number(s) it is used in.

A simple work-around could be to store the Frame names in the Path-Object Properties?

**Comment by senshu** [comment]
Sozi 13 is no longer developed. I am now closing all issues related to Sozi 13.
Please try Sozi 15 and open a new issue if you think that your problem still deserves to be addressed.
