### ISSUE TITLE
Option for disable keys triggers in player.

### ISSUE THREAD

**Issue by mabeett** [senshu/Sozi#208]
I am using sozi from the launchpad repository in ubuntu 12.04.

I would use sozi with links for interactive behaivor, here a simple example:

https://dl.dropboxusercontent.com/u/3901433/sozi/cuestionario_draft.svg

But I need disabling the keys and mouse button triggers. If the user press left, or middle button the flow gets broken.

Thanks

**Comment by senshu** [comment]
Implemented in Sozi 17.11
