### ISSUE TITLE
Video sozi extras: special characters in file names

### ISSUE THREAD

**Issue by gregnaysien** [senshu/Sozi#209]
Hello
I'm french but i can try in english to explain my problem.
Impossible to ad a video. In inkscape a go on extension-sozi extra - add a video.
It's doesn't work. I'v got this message : 
Traceback (most recent call last):

  File "sozi_extras_media.py", line 115, in <module>

    effect.affect()

  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 215, in affect

    self.effect()

  File "sozi_extras_media.py", line 66, in effect

    self.add_media()

  File "sozi_extras_media.py", line 92, in add_media

    v.set(inkex.addNS("src", "sozi"), unicode(self.options.src))

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 18: ordinal not in range(128)

I didn't find any tuto or exemple anywhere too antersdan my pb.
Is there some one,king enought too explain to me the good way too add a video ?

Thk you.
Greg

**Comment by senshu** [comment]
The extension has been updated to be compatible with the new presentation format in Sozi 15.
Feel free to reopen this issue if the problem still exists.
