### ISSUE TITLE
Presenter console

### ISSUE THREAD

**Issue by ejvindh** [senshu/Sozi#211]
I realize that "new features" are not your prime concern right now. I thought, however, I would mention it still though. Then perhaps some day in the future you (or others) can get back to it :-)

Sometimes when presenting it is nice to have some notes that are not shown to the students. Would it be possible to create an extra window containing both the "current view" and "notes-for-the-presenter"? Ideally also a representation of the "next view".

Something along the lines of Regebro's "impress-console" (I don't know if it can be transferred to sozi-presentations): https://github.com/regebro/impress-console

Or, more minimalistically: https://github.com/hakimel/reveal.js#speaker-notes

**Comment by roggan87** [comment]
Hi folks!

I've been hacking on a remote control for sozi myself, and it's shaping up. I'm not sure how to use kai-wegner's fork, so sorry if I'm duplicating some work here. I've implemented buttons to move between slides, the frame list, a timer and the keyboard shortcuts. I plan to add previews of previous, current and next frame, as well as comments for the current frame.

Everything is integrated into the *.sozi.html file, just as the player itself, so you don't need any extra software to use it. In it's current state it adds ~5kb to the file, so nothing to worry about :)

[Click here to see a demonstration of it](http://roggan87.github.io/remote.html). Open the remote control by clicking the icon in the frame list. I'd also like to map [c] to open it. So far I've only hacked on the html file itself, so I haven't yet implemented this is the sozi code, but that's the next step.

Please let me know if you have any suggestions, complaints, etc. Also, if this work is doomed to be rejected due to kai-wegner's work, please let me know!

**Comment by ejvindh** [comment]
I find this very promising :+1: . Esp. if you add the sketched prev/curr/next and the comments :)

One challenge, though, is that sometimes the information on presenter consoles tend to become too small, because we want all too much information. So if it was possible to make the consoleview configurable by the presenter, that would be ideal (to make it possible for him/her to decide what to use, and what to close down).

But certainly, one thing at a time ;)

**Comment by roggan87** [comment]
Thanks! I see what you mean, good point. I think it would be nice to have some preset layouts to switch between in the presenter. I also think one has to be very selective what to display depending on the window size, so making the remote control fullscreen gives other possibilities.

**Comment by zenny** [comment]
@roggan87: Very interesting implementation. Where is your code repo or binaries? Thanks for pointing me.

**Comment by roggan87** [comment]
Thanks @zenny! Hopefully it'll make it into the official Sozi repo. I've made a pull request #325. Meanwhile you can find it at https://github.com/roggan87/Sozi, but I have no plans to maintain a separate fork.

**Comment by zenny** [comment]
Does your master commit can build into desktop application as well as
executables with the features you updated?

Like with the senshu/Sozi, I am getting errors while trying 'npm install'.

Any inputs?

**Comment by kai-wegner** [comment]
@roggan87 
My implementation is a add-on for Sozi (that's why it's called catchi) and is a presenter console with some additional functionality like templating and presentation management. (filemanagement, speaker notes, full presentation time, slide presentation time, second-screen support, aso.)
One could use it as a company wide, server-side Sozi presentation application or framework.

Currently I'm facing a heavy workload but will work on that project in 2016 for sure.

Your work should not be rejected, instead it can be useful for catchi.
My framework adds everything it needs to sozi.html file also. :smile:

**Comment by roggan87** [comment]
@zenny, it does build into executables and desktop application. I also had trouble compiling Sozi in the beginning, but [this thread](https://groups.google.com/forum/#!topic/sozi-users/H1J0AgVMuwg) got me going in the right direction. Note that the changes are implemented in the dev branch, not the master. I uploaded some compiled binaries for you with the *inofficial changes* [here](https://drive.google.com/open?id=0B-U60NJCrnPEVTVNX1FMN0RSZ2M).

@kai-wegner, thanks for clarifying! Interesting approach. I couldn't manage to open the presenter console though, not sure what I did wrong. I'd like to make my work compatible with catchi as much as I can.

**Comment by kai-wegner** [comment]
@roggan87 did you turn your popup-blocker off?

**Comment by roggan87** [comment]
Well I didn't receive any message about popups being blocked, but on the other hand I'm not sure how to open it, is it by pressing [p]?

**Comment by kai-wegner** [comment]
@roggan87 If you press play, catchi should open two windows - one with the presentation, the other with speaker notes and time measures.

**Comment by roggan87** [comment]
@kai-wegner, I see, it works now in Firefox. Thanks.

**Comment by roggan87** [comment]
Long time without any update... [Here's a presentation][1] that shows how to use the remote control in it's current state. All functionality there is available in the pull request #325.

To get the unofficial binaries of this branch, [look here][2].

   [1]:  http://roggan87.github.io/presenting-the-sozi-remote-control.sozi.html
   [2]:  https://drive.google.com/drive/folders/0B-U60NJCrnPEVTVNX1FMN0RSZ2M

**Comment by ejvindh** [comment]
This is VERY convincing indeed!

One little bug, though (I think): At slide 14 of your presentation, nothing happens when I drag "the little handle"? (Firefox, Google Chrome, Ubuntu 14).

**Comment by roggan87** [comment]
Thanks! Um I guess it wasn't that clear. Try this:

1. Open up the remote control.
2. Maximize it (so you get the layout where the speaker's notes are shown).
3. Look for a small dotted triangle/striped triangle/filled triangle below the "next preview"
4. Drag it left or right to alternate the proportions between previews and notes.

Is that working?

**Comment by ejvindh** [comment]
Ahh, yes. Now I found it, and it is working :)

Very nice feature, if you want to change the proportions between slide-view and notes.

**Comment by roggan87** [comment]
Nice. I realize it's not that obvious how it works (and hard to notice the small handle if one does not know about it, but hopefully it can become useful. It's a clean and simple way to make use of css and avoiding more javascript libraries etc.

**Comment by senshu** [comment]
This feature has been kept in a separate branch that is no longer in sync with master.
I think that there were two reasons for not integrating it:

1. I thought that the implementation could better benefit from the internal APIs of Sozi.
2. I did not like the idea to ship the presenter console code inside each presentation. I tended to prefer how [catchi](https://github.com/kai-wegner/catchi) worked as a separate tool to load and control presentations.

I have reused part of the code by @roggan87 and I have made a simple prototype of a web page where you can load a presentation and play it: http://sozi.baierouge.fr/presenter/
You can find the code in the `extras/presenter` folder of this repository.
You will need to accept popups and possibly disable your ad blocker to use it.

**Comment by senshu** [comment]
In ed3beee498605b54268c8442357fafab644c0585, the presenter is saved as an HTML file along the Sozi presentation HTML.

**Comment by ejvindh** [comment]
Hi senshu.
Sorry for taking so long to respond to this amazing work of yours. Unfortunately I'm not teaching very much this year, so I don't have so many occasions to look into this.

I'm very glad that this has become a part of the official branch. I took a peek into the underlying code, and I must admit that I'm quite impressed by the simplicity of your solution on the structural level.

However, as to the usability of the solution, I'm afraid that the display of the presently shown frame will be too small, so that the presenter will have to turn away from the audience in order to see what they are able to see.

I realize that there is an issue about responsiveness here: You cannot predict the sizes of neither the first and second screen. Just as presenters will vary in how many notes they want in the note-section. However, I think that this issue was to some extend solved in @roggan87 's solution by making the frames resizable. The presenter can then at the beginning of the presentation choose his/her preferred sizes.

**Comment by senshu** [comment]
Thanks for commenting.
I agree that the readability of the presenter view is far from optimal. It needs to make a better use of the available screen space.
I have not used this feature in live conditions, and I expect users to provide feedback to help improve it.

**Comment by ejvindh** [comment]
[Sozi_1904_new.zip](https://github.com/senshu/Sozi/files/3118631/Sozi_1904_new.zip)
I did a little playing-around with the css and js in a sample-presentation. Now, css is really not my strongest coding-environment, but I think something along the lines of the attached, could give some extra usability. Should probably be supplemented with a couple of @media-tags in cases where the presenter-screen is in portrait.

Feel free to use what you like, and ignore/trash the rest :)

**Comment by ejvindh** [comment]
Thanks for your new work on this issue in 19.11. I've done some tests on it, and it seems to me that it works best in Firefox (I didn't manage to have the views change in Chromium...). However -- personally I still miss the ability to resize the views :)

The following results are nested: (1) indicate tests in Chromium-based browsers; (2) indicate Firefox:

*** Summary of your problem or feature request**
Testing the presenterConsole in pre-release: 19.11

*** Version of Sozi and other relevant software**
Sozi-19.11.23-1574531954-linux-x64.tar.xz
xbuntu 18.04.3 LTS

(1) Brave Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit). Also tested on other Chromiumbased browsers like Chrome (70.0.3538.77 (Officiel version) (64-bit)) and Iron (66.0.3450.0 (Udviklerversion) custom (64-bit))

(2) Firefox 71.0 (64-bit)

*** Steps to reproduce the problem**
http://uploads.ejvindh.net/sozi1911_test.zip

*** Expected behavior**
(1) That views will change during playback of the presentation. To be able to change the sizes of the views.
(2) To be able to resize views of presenternotes and presented windows


*** Observed behavior**
(1) No changes in the presenterwindow. However the playback/-forward buttons seem to work.
(2) Cannot resize windows


*** Hints and solutions**
(1) Fun-fact: The views of the previous-current-next-window all show the first view of the presentation. However, it is possible to click upon the slide-number at the top-left corner and change each of the the views manually.

**Comment by ejvindh** [comment]
addon:
Editor-bug: Clicking on the questionmark on the right of "Notes" promises a list of formatting shortcuts, but none are shown.

**Comment by senshu** [comment]
@ejvindh Thanks for your comments. I have moved them to new issues: #467 and #468. Let's continue this conversation there.
