### ISSUE TITLE
sozi2pdf parserror

### ISSUE THREAD

**Issue by ajeantet** [senshu/Sozi#213]
Hi,

First, thank you for creating such a wonderfull tool !!

When I try to use sozi2pdf.js I get a parse error (and nothing happens ; in /tmp it creates a folder which remains empty), and then a few more lines when i kill it (Ctrl C) : 

<code>~/Bureau/Presentations/sozi$ python sozi2pdf.py test.svg
SyntaxError: Parse error
^C
Traceback (most recent call last):
  File "sozi2pdf.py", line 105, in <module>
    subprocess.call(["phantomjs", js, input_file_name, tmp_dir, str(width_px), str(height_px), options.include, options.exclude])
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1291, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
</code>

Im using : 
- Sozi 13.10-03192715
- python 2.3
- phantomjs 1.9.2

I guess that I've just missed something very trivial, haven't I ?

Any help would be welcomed !

**Comment by senshu** [comment]
This issue is related to Sozi 13.10.
sozi2pdf will not be fixed for this version.

With the release of Sozi 15, I will upgrade sozi2pdf to make it work with the new presentation format. Then you will be free to reopen this issue if it does not work with the new version.
