### ISSUE TITLE
Problem Sozi / Inkskape

### ISSUE THREAD

**Issue by Neophite07** [senshu/Sozi#222]
Hi,

I am French. Sorry for my bad knowlledge in your language.
I write you, because I didn't find a French site. 

I downloaded Inkscape for windows 32 bits (mine is windows 8.1, 64 bits) , as indicated on the official site : Http:\\sozi .baierouge.fr

Could you help me, because I have a problem with Sozi:
1)	Clic, option « Extensions » and « Sozi », this message appears :
"Traceback (most recent call last):   File "sozi.py", line 29, in <module>     import sozi.upgrade   File "C:\Program Files\Inkscape\share\extensions\sozi.py", line 29, in <module>     import sozi.upgrade ImportError: No module named upgrade" 

2)	Clic option « Extensions »,  « Sozi extras», and « upgrade », this message appears 
"Traceback (most recent call last):   File "sozi_extras_upgrade.py", line 27, in <module>     import sozi.upgrade   File "C:\Program Files\Inkscape\share\extensions\sozi.py", line 29, in <module>     import sozi.upgrade ImportError: No module named upgrade"

 As indicated on the official site, I have douwnloaded (but I don't know if it's right) on the steps:
2) Python-2.7.8.msi
3) LXML-3.2.4.win32-py2-7.exe (mds)
4) PyGTK all in one version 2.24.0.win32-py2.7.msi
8) Sozi version 13

Below, the sceen's copies of my files.
Thank you for your help.

![inkscape 1](https://cloud.githubusercontent.com/assets/8232581/3655654/95245884-117c-11e4-9e59-a2724f6e8591.png)

![inkscape 2](https://cloud.githubusercontent.com/assets/8232581/3655698/25aa9c9c-117d-11e4-8547-ea21d1b1452d.png)

![inkscape 3](https://cloud.githubusercontent.com/assets/8232581/3655701/2f0be5f2-117d-11e4-91f9-445bf60295ff.png)

![inkscape 4](https://cloud.githubusercontent.com/assets/8232581/3655709/45d07a64-117d-11e4-8720-9975351919fb.png)

![inkscape 5](https://cloud.githubusercontent.com/assets/8232581/3655713/5310eaba-117d-11e4-878d-d2eec4fd68d5.png)

![inkscape 6](https://cloud.githubusercontent.com/assets/8232581/3655717/5d6ed4e0-117d-11e4-81d6-6c5ae78d9cd2.png)

**Comment by senshu** [comment]
Sozi 13 is no longer developed. I am now closing all issues related to Sozi 13.
Please try Sozi 15 and open a new issue if you think that your problem still deserves to be addressed.
