### ISSUE TITLE
impossible video export 

### ISSUE THREAD

**Issue by cobacdavid** [senshu/Sozi#234]
Hi,
i use the script sozi2video.js  to export my sozi svg to a ogv video.
Here's what i get:
    python sozi2video.py presentation_generale_sozi_2.svg -W 1600 -H 900 -o mavideo.ogv
    sozi2video.js> Exporting frame: 1
    sozi2video.js> Exporting frame: 2
    sozi2video.js> Exporting frame: 3
    sozi2video.js> Exporting frame: 4
    sozi2video.js> Exporting frame: 5
    Writing video to: mavideo.ogv
    Traceback (most recent call last):
      File "sozi2video.py", line 62, in <module>
        "-i", frame_pngs, "-b", options.bit_rate, output_file_name])
      File "/usr/lib/python2.7/subprocess.py", line 522, in call
        return Popen(*popenargs, **kwargs).wait()
      File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

I uses ubuntu 14.04 with prebuild inkscape 0.48.3.1 and i've build sozi 13.11

Thanks for any help !
David

**Comment by senshu** [comment]
I am closing this thread. Please feel free to reopen it if you think your problem has not been addressed properly.
