### ISSUE TITLE
Sozi 14 doesn't work on Ubuntu 14.04 without library modification

### ISSUE THREAD

**Issue by edmcdonagh** [senshu/Sozi#236]
libudev.so.0 is removed in 14.04, but there is a libudev.so.1

Not really an issue with Sozi, more node.js (or something else) and Ubuntu (I think). One solution is to create a symlink:
http://askubuntu.com/questions/288821/how-do-i-resolve-a-cannot-open-shared-object-file-libudev-so-0-error

**Comment by senshu** [comment]
The dependency to libudev has been removed in node-webkit 0.12.
I will close this issue as soon as I release a new prototype of Sozi with the latest version of node-webkit.
