### ISSUE TITLE
Sozi 14: Feature request - HTML title

### ISSUE THREAD

**Issue by edmcdonagh** [senshu/Sozi#242]
I don't think there is a way in the current version of Sozi 14 to add a title to the presentation.

The HTML that is produced has a title element value of 'Untitled'. I would like to be able to set this in the Sozi 14 interface.

**Comment by roggan87** [comment]
Glad to hear there is a way! To me it would be more convenient to fetch the filename as title, unless it is specified in the metadata. So the title for "sozi-presentation.svg" would simply be "sozi-presentation". If the same file would have the title attribute set in the metadata to "Sozi presentation", that would have higher priority.

Didn't want to file a new issue for this though, before I hear your thoughts.

**Comment by joakimtaby** [comment]
Personally I am pretty happy with the way it is now, giving the author freedom to call it what he wants.
