### ISSUE TITLE
Sozi does not refresh (Mac)

### ISSUE THREAD

**Issue by Benjou** [senshu/Sozi#249]
Hi!

I'm running Sozi on a Mac, and the experience is great!

One thing that could be better is the way it handles load, save, etc.

The release note states: "There is no Save button. The editor saves the current document automatically, each time the window loses focus, and before quitting. If you modify the SVG document while Sozi is running, it will be reloaded automatically when Sozi gets the focus again."

However that is not what I experience. losing and regaining focus does not work. I have to close and reopen everytime to have the proper html file saved and svg file reloaded.

Could it be a Mac specific problem?
Could there be a way to have a "reload svg"  and a "export to html" button to circumvent this problem (if it is indeed mac-specific)

Cheers!

**Comment by senshu** [comment]
"Save" and "Reload" buttons have been added to the current development version. They will be available in the next release.
