### ISSUE TITLE
Sozi -13 - End of Life?

### ISSUE THREAD

**Issue by tvld** [senshu/Sozi#261]
Do we understand correctly that Sozi -13 is the latest Inkscape related version?

If so, are you aware of altenative? We really dont want a stand-alone. that Sozi-14 seems to be: we use Inkscape,

**Comment by senshu** [comment]
Sozi 13 is no longer developed. I am now closing all issues related to Sozi 13.
Please try Sozi 15 and open a new issue if you think that your problem still deserves to be addressed.
