### ISSUE TITLE
background color not shown in Sozi 14

### ISSUE THREAD

**Issue by edgimar** [senshu/Sozi#266]
I am trying to work with an Inkscape produced SVG file using the online version of the Sozi 14 editor, and although I have set the background to be black in the SVG, the background appears as white in the editor.  As a result, I can't see any of the white text I have in the SVG.

**Comment by senshu** [comment]
I have just updated the web site with indications to set a background color in Inkscape.
http://sozi.baierouge.fr/pages/faq.html

Please tell me if you need more explanations.
