### ISSUE TITLE
Disable mouse zoom in <object> or <embed> in HTML document

### ISSUE THREAD

**Issue by lucker999** [senshu/Sozi#272]
Hi guys, 

Sozi is amazing tool to impress and I love use it for complicated subjects.
Recently I managed to embed the sozi presentations into the website pages and faced inconvenience. Since the best way to use sozi is as wide as possible, it makes difficult to scroll down the page with the embedded presentation.

[I read](http://stackoverflow.com/a/21503151) that using the tags object or embed with svg make possible to to obtain a reference to SVG. Also, here on [GitHub](https://github.com/senshu/Sozi/issues/51) was mentioned some similar issue. Alas, I'm not so savvy in js to understand how to implement it for my issue.

Could you please advise a solution to disable mouse zooming over the embedded sozi presentation? I believe I'm not alone with this request, but lack of programming skills make my visitors frustrating with svg behaviour :)

Thank you!

**Comment by lucker999** [comment]
Actually I have find how to manage this by editing svg file.

You need to open the final ready-for-upload edition with some text editor (I use notepad2), and search for "onWheel". 
In my case it has two pieces. 
1. between and include from 'function onWheel(evt)' and 'evt.preventDefault();
    }'
2. two lines 
	* svgRoot.addEventListener(&quot;DOMMouseScroll&quot;, onWheel, false); // Mozilla
	* window.onmousewheel = onWheel;
After I have commented this two pieces and save the file it has no reaction on mouse wheel when is showed in a  browser.

Would be great to have an opt-out option in the sozi to disable this without searching the code though.

**Comment by senshu** [comment]
> Would be great to have an opt-out option in the sozi to disable this without searching the code though.

There is already a feature request for this: #1

**Comment by senshu** [comment]
Implemented in Sozi 17.11
