### ISSUE TITLE
Use jQuery inside the sozi SVG file?

### ISSUE THREAD

**Issue by maronin** [senshu/Sozi#273]
Is it possible to use jQuery in the SVG file? I don't know how to do it. 

I tried including jQuery in my html, and embedding my SVG into my html. That didn't work. 

I basically want to use jQuery inside this tag 

``  <script
     ns1:version="13.11-30213629"
     id="sozi-script"> </script>
``

**Comment by senshu** [comment]
As far as I remember, jQuery does not work with SVG.

Is there a specific reason for you to modify the content of the Sozi `<script>` tag?
Why don't you add your own `<script>`?

**Comment by maronin** [comment]
I guess it's just for the "write less, do more" aspect. But if there is a way to use jQuery outside of the SVG file and still access the Sozi functions (like moveToFrame, jumpToFrame, moveToNext, etc. ), that would be awesome. I want to add some functionality like hiding frames/layers, but I want to use jQuery for animations to make my life easier.

**Comment by senshu** [comment]
Sozi 13 is no longer developed. I am now closing all issues related to Sozi 13.
Please try Sozi 15 and open a new issue if you think that your problem still deserves to be addressed.
