### ISSUE TITLE
Impossible to use layer

### ISSUE THREAD

**Issue by magicvince** [senshu/Sozi#274]
in sozi 15 (linux 32b), i'm unable to use the layer.
I use layer in my svg file, but when I choose it with the drop box to add one of my layer, the layer stay to "default".
The objects seems to be on the same layer.

**Comment by senshu** [comment]
Can you send me a sample SVG document, so that I can reproduce the problem?

**Comment by magicvince** [comment]
Tu trouveras deux fichiers qui m'ont servi à tester les layers ici : http://demo.ovh.eu/fr/b9b8acd7ebf6bed64f21d8a90fa01369/

(two files in an archive to try to reproduce de problem)

**Comment by senshu** [comment]
Chez moi, Sozi 15 fonctionne correctement avec les deux fichiers.
Je peux ajouter les calques et les manipuler.

J'ai aussi essayé avec [la démo en ligne]( http://sozi.baierouge.fr/demo/) et je n'ai pas remarqué de problème.

**Comment by magicvince** [comment]
D'accord pour les fichiers qui fonctionnent avec la version en ligne et avec la version Sozi-14.10.292105-linux32, mais avec la version Sozi-15.02.112134-linux32, impossible de jouer sur les layer (je fais tourner la 14 et la 15 sur la même config MintDebian 32bits)

**Comment by magicvince** [comment]
je viens de récupérer la version Sozi-15.02.201752-linux32 et c'est ok, les manips se font très bien

**Comment by senshu** [comment]
OK. Sozi 15 n'est pas encore complètement stable et il y a des mises à jour assez fréquentes.
Il est préférable de tester le dernier prototype avant de signaler un problème.

Là, c'est un peu de ma faute ; je n'annonce pas toujours publiquement la mise en ligne d'une nouvelle version.
