### ISSUE TITLE
Frame error in the presentation

### ISSUE THREAD

**Issue by fabiokotowiski** [senshu/Sozi#275]
I created a file in Inkscape, version 0.48.4 R9939, which has 15 frames and the presentation goes just fine till frame 13. The frame 14 has a error. It doesn't work as I want. I want it to zoom it but it's showing the middle of the whole page instead. I think, though I'm just a user, it seems like a little bug in the source code. Could you help me with that?

(I attached 3 images below. The first one is frame 13, the second one is frame 14 and the last one is frame 15)

Thanks in advance.

![captura de tela de 2015-03-01 18 27 33](https://cloud.githubusercontent.com/assets/11260965/6432909/a9da27a4-c040-11e4-90fd-ab4e77366fe7.png)
![captura de tela de 2015-03-01 18 28 10](https://cloud.githubusercontent.com/assets/11260965/6432912/bd49d1e0-c040-11e4-898b-0dce2dad84bb.png)
![captura de tela de 2015-03-01 18 28 32](https://cloud.githubusercontent.com/assets/11260965/6432915/cc57f7b6-c040-11e4-98bb-19d95b8022f5.png)

**Comment by senshu** [comment]
I need to try it myself to find the bug.
Can you send me a copy of that SVG document, or another document with the same bug?

**Comment by fabiokotowiski** [comment]
Hi, senshu! I uploaded the file on Mega. Here's the link: https://mega.co.nz/#!iEhEgSQI!_nq5eLJ0U8ymS9IlFt08i6s4cxwlah06ASeVWgznNXw
It's the original document with the bug I reported.
Thank you very much for your help.

**Comment by senshu** [comment]
Hi. As far as I can tell, this is not a bug in Sozi.
I would suggest that this is a rendering issue in web browsers.

There is a small element with id "path6322" in your document. It is a `<path>` element with only one end. It seems that Firefox and Chrome cannot reliably compute the size of this element, so they provide wrong information to Sozi.

You can find that element using the "Find/replace" dialog of Inkscape.
Removing it solves the issue.

**Comment by fabiokotowiski** [comment]
Hi, Senshu! Your instructions solved the issue. Thank you for your help and congratulations on Sozi. It's great tool. I want to create more presentations soon.
