### ISSUE TITLE
sozi2pdf_pptx

### ISSUE THREAD

**Issue by ejvindh** [senshu/Sozi#276]
I use Sozi very often in my presentations. Generally the slides receive good reviews from the students. However, increasingly often they query me to upload the files as powerpoint files, because that would make it possible for them to annotate directly in the files.

As a first solution, I turned towards sozi2pdf, but some students are unfamiliar with the pdf-tools that allow for pdf-annotations. I've thus invested some time in enhancing your sozi2pdf so that it could generate both pdf and pptx files: sozi2pdf_pptx
http://uploads.ejvindh.net/sozi2pdf_pptx.zip

In addition to the dependencies of phantomJS & pdfjam, it adds a dependency of python-pptx:
    https://python-pptx.readthedocs.org/en/latest/
    https://github.com/scanny/python-pptx/
    https://pypi.python.org/pypi/python-pptx
(install with: pip install python-pptx)

It runs very much like sozi2pdf, however it now generates two files: *.pdf and *.pptx

I've furthermore added an extra format: "notes" -- which can be used when the files are not to be printed.

If you like the feature, feel free to implement it as you like. I've added comments to mark all the changes made in the original code.

I realize that your latest developments might suggest that you will not go into this, since the conversion tools may need complete re-writes. But I'm still on the Inscape-addon version. :-)

**Comment by senshu** [comment]
Thanks for this contribution. I really like this idea.
I didn't know about python-pptx

> I realize that your latest developments might suggest that you will not go into this, since the conversion tools may need complete re-writes.

Yes, sozi2pdf will be rewritten. In the recent developments, I have favored the use of JavaScript in the Sozi editor as well as the player. I was also considering replacing Python with JavaScript in conversion tools. A JavaScript alternative to python-pptx would be great.

**Comment by ejvindh** [comment]
"A JavaScript alternative to python-pptx would be great."

I'm quite new in JS, but maybe https://www.npmjs.com/package/officegen has some of the features, you are looking for?
