### ISSUE TITLE
i18n broken in application build (tested on mac os x)

### ISSUE THREAD

**Issue by kai-wegner** [senshu/Sozi#278]
Hi senshu,

please note that the application is broken under the current dev.-commit 199ef8b404e561ce10d92a88c0243425f2d5ac46 
Please find my comment in the file js/i18n.js here:
https://github.com/senshu/Sozi/commit/199ef8b404e561ce10d92a88c0243425f2d5ac46#commitcomment-10590396

```sh
[32856:0406/223641:ERROR:nw_shell.cc(335)] ReferenceError: $ is not defined
    at Object.init (file:///Applications/Sozi.app/Contents/Resources/app.nw/js/editor.min.js:929:20)
    at file:///Applications/Sozi.app/Contents/Resources/app.nw/js/editor.min.js:849:18
[32856:0406/223641:INFO:CONSOLE(929)] "Uncaught ReferenceError: $ is not defined", source: file:///Applications/Sozi.app/Contents/Resources/app.nw/js/editor.min.js (929)
```

*I disabled minification/uglify for the stacktrace*

I could not find a fix without removing the import-mechanism and embedding the JS by hand. Maybe you can figure it out more easily. 
I'll wait for a fix to test my contributions with the current commit to submit a small pull request which will help me building a presenter-framework for Sozi. :smiley: (remember #210 ?)

**Comment by senshu** [comment]
Unfortunately, I can only test Sozi on Linux and Windows 7.
I could not reproduce the issue on these platforms.

I will try to investigate the possible causes based on the information in your stack trace.

**Comment by kai-wegner** [comment]
I thought that.
Building it on linux worked fine and before that commit everything was ok on my mac, also.

You can reach me via google-hangouts or IRC ( freenode / ki__ ) if you need some "real-time" collaboration on this. :wink:

**Comment by senshu** [comment]
Currently, I am clueless. Everything looks fine in the OS X archive and I see no reason why jQuery should behave differently from the previous builds.

I'll get back to you as soon as I can. I will not have a lot of time to work on Sozi until the end of this week.

**Comment by kai-wegner** [comment]
No worries - I have some spare time in the evening and on my flights (at the airport).
I'll try to setup a test-case for that issue and figure out why this works on linux by debugging the jQuery hierarchy. Did not put much effort in this, because I was afraid that you could bring a fix in a few minutes. We'll fix that bug. :wink: 

Strange thing is that after I check out the commit before the broken one (on mac) everything works again. :monkey_face: 

Looking forward to create a pull request!

**Comment by senshu** [comment]
Hi, @kai-wegner 
In the latest commit, I have changed the loading mechanism for the locale data.
Now, locales are included in the JS of the editor and are no longer loaded using jQuery and AJAX.
I made that change to solve another issue, but I suppose it will solve yours as well.

**Comment by kai-wegner** [comment]
@senshu 
Meeeh. I rechecked everything after running into the next reference error and found myself without `bower_components` at buildtime. :-1: Sorry! 
Good to know that this fixed another bug, so your effort was not useless. 

My pull request should help to get rid of such stupidity and improve build and player customization  - please see #279 .

Thanks in advance and kind regards,
Kai
