### ISSUE TITLE
Animations less "smooth" in Sozi15

### ISSUE THREAD

**Issue by ejvindh** [senshu/Sozi#282]
Being an incarnated user of Sozi13, I've been somewhat reluctant moving on to Sozi14/Sozi15. However this evening I gave it a go (Sozi-15.04.191623-linux64.tgz) and I must admit that the user interface looks quite promising.

However, I noticed one setback: The transitions between the different views seem to be less smooth than they used to be. I imported an old Sozi13-svg, and added a couple of extra views, and the transitions between the new views was less smooth (especially in Firefox). I use Ubuntu 14.04.

I've uploaded an example:
http://uploads.ejvindh.net/sozi/00_skyen.sozi.html
http://uploads.ejvindh.net/sozi/00_skyen.sozi.json
http://uploads.ejvindh.net/sozi/00_skyen.sozi.svg
(view 2-4 are the newly added views)

**Comment by senshu** [comment]
The Sozi player is basically the same in Sozi 15 as in Sozi 13, except for the "clipping" feature. I think I know how I can fix this issue.

BTW: the link to your SVG file is broken.

**Comment by ejvindh** [comment]
Sorry, correct link is: http://uploads.ejvindh.net/sozi/00_skyen.svg

**Comment by ejvindh** [comment]
(the svg-file being the original Sozi13-file...)

**Comment by senshu** [comment]
Thanks. Currently, I see no significant difference between Sozi 13 and Sozi 15 with your files on my computer.
However, I have made a small change to the player to address this issue. You can [try the latest build ](https://drive.google.com/open?id=0ByRUreHgekjMfjFrMmhGbzUxbGtlQVVxaXFXNzhwODFWV09MOXdLRWxUcUVMNVRSdmhXYms&authuser=0) as soon as it is uploaded and please tell me if you notice an improvement.

**Comment by senshu** [comment]
You can also download [the HTML document that I have generated from your presentation](https://drive.google.com/file/d/0ByRUreHgekjMajVGQzc3YVlkN3c/view?usp=sharing) using the latest version of Sozi.

**Comment by ejvindh** [comment]
Hmmm, I think I've made a wrong analysis. Still when I open the file that you uploaded, I think the "old" animations are more smooth than the new ones. But upon further reflection, it seems to be because the new views navigate between more complex content (showing more of the entire view). At least when I try to imitate the old animations, but programmed with the new editor, there is no difference.

It is thus probably not caused by the new editor. Sorry if this has caused you too much trouble.

BTW, during my analyses today, I noticed that the new editor had trouble loading the 00_skyen.svg file if I prepared it with "object to path" on the entire file first. But maybe we should wait submitting bugs until you have published a more mature version?

**Comment by senshu** [comment]
> It is thus probably not caused by the new editor. Sorry if this has caused you too much trouble.

It's OK. I had planned to make that change in the clipping feature anyway.

> I noticed that the new editor had trouble loading the 00_skyen.svg file if I prepared it with "object to path" on the entire file first. But maybe we should wait submitting bugs until you have published a more mature version?

I think that I will announce a beta release of Sozi 15 in the coming weeks.
Bug reports are welcome. It will help if you indicate the complete version number.

**Comment by senshu** [comment]
I have checked your document and I see that the main layer (Layer1) is almost empty. Most of the SVG elements belong to no layer at all! Sozi should handle this situation correctly in most cases. But when texts are converted to paths, Inkscape generates a "group" element for each text element. Sozi incorrectly assumes that each group is a layer.

This has two consequences:
* The Sozi player has to manage many layers and takes a long time to process your document before playing it.
* The text is not displayed correctly when the presentation is played.

I have uploaded modified versions of your presentation here:
https://drive.google.com/folderview?id=0ByRUreHgekjMSUw5aXpKdjZrUVE&usp=sharing

**Comment by ejvindh** [comment]
I've never been very conscious about layers when creating my slides in Inkscape. Maybe I should change that -- if that will lesten the work of the Sozi player, and make the text show more precisely.

I've often used the "object-to-path" trick because of the exact reasons you mention: otherwise the animations become to slow and text (esp. (but not exclusively) below font-size 10) shows pretty ugly.

Thanks for the uploads. They are very illuminative.

**Comment by senshu** [comment]
I am closing this issue. Please feel free to reopen it if you think your problem has not been properly addressed.
