### ISSUE TITLE
How to hide a layer part way through a presentation.

### ISSUE THREAD

**Issue by NigelCunningham** [senshu/Sozi#283]
Hi.

I love the new editor, but one thing I've not yet figured out is whether it's possible for us to hide a layer in a particular slide. To give a concrete example, I have very large text in a title, on a layer called Title. On the first slide, I want to show that layer and hide 'Layer1', which contains the body of the presentation. When I transition to the second slide, I might want to switch layers, zooming through the big text to the smaller text and hiding the title.

I've tried clicking and double clicking on the intersection of layers and frames, but that doesn't seem to do anything. I also sometimes see a link on the left side of these intersections, but it doesn't seem to do anything either.

Am I just trying the wrong thing?

Thanks!

Nigel

**Comment by senshu** [comment]
Currently, there is no way to *hide* a layer during the presentation. Usually, I simply move the camera to an empty region of that layer.
In the editor, clicking at the intersection of a layer and a frame allows to operate on this specific layer in this specific frame only. When you drag the mouse in the *preview* area, only the selected layer will move.

**Comment by senshu** [comment]
Commit 974847277e54f805f19dc81d3ce4b7e2af582431 adds the following feature: in a given frame of your presentation, you can modify the opacity of each layer. For instance, you can choose to make one layer fully transparent while another is fully opaque. Transitions between frames where a layer has different opacities will produce a fade-in or fade-out effect, unless you choose one of the "step" timing functions.

This feature is avaliable in [Sozi 15.04.242301](https://drive.google.com/open?id=0ByRUreHgekjMfjFOWjJIbFZfVFRVcVRRRDdJNzFMcjd6eUM1M005Qm9fam9RcDhvZmZORG8&authuser=0)

**Comment by NigelCunningham** [comment]
Great! Thanks!

Nigel

**Comment by Hash--** [comment]
Thank you for this feature. Could you add a sample using it in the repository ? I've got some troubles under MS Windows 64 : all the additional layers except the first are not visible. So I would like to see a working .svg made with Sozi 15 to compare.

**Comment by senshu** [comment]
Hi, Julien.

2015-05-04 10:14 GMT+02:00 Julien Hillairet <notifications@github.com>:

> Thank you for this feature. Could you add a sample using it in the
> repository ? I've got some troubles under MS Windows 64 : all the
> additional layers except the first are not visible. So I would like to see
> a working .svg made with Sozi 15 to compare.
>

I'll try to provide an example in the next few days.

Guillaume

**Comment by senshu** [comment]
@Hash-- 
You can take a look at `using-layers.svg` in [the samples folder (dev branch)](https://github.com/senshu/Sozi/tree/dev/samples).

**Comment by Hash--** [comment]
Thank you. I'm still perturbed by the way layers works. I understand now
that the layer does not have to be located in the same place than the main
frame. I thought instead with a MS ppt approach, putting the element I want
to show/hide in a new layer and located at the precise place I want...



2015-05-10 18:21 GMT+02:00 Guillaume Savaton <notifications@github.com>:
