### ISSUE TITLE
Sozi 15 for IE?

### ISSUE THREAD

**Issue by gamzatti** [senshu/Sozi#288]
Hi there,

I've only just stumbled across Sozi and it's a great tool.

However I can't get a project I made with 15.05 to work in Internet Explorer (I've tried IE 9 and 11) - this may well be a known issue. I don't use IE but some of the audience for my project unfortunately do.

Sozi 13 seemed to be fine for IE (going by the preview on http://sozi.baierouge.fr/pages/10-about.html), but having already built the presentation in 15 I thought it might be easier to add some sort of workaround to add to the html doc rather than build the project from scratch in 13, if that's likely to work?

Thanks for any help you can give me!

![sozi screenshot ie](https://cloud.githubusercontent.com/assets/1896146/7655315/8fbcbc6e-fb1a-11e4-8de3-8b40c874d0b2.png)

**Comment by senshu** [comment]
To be honest, I have not tested Sozi 15 in IE at all.
I will investigate try that ASAP.

**Comment by emilycoats** [comment]
Cool.
FYI it turns out the idea of making an interactive presentation has been vetoed anyway, and I am now just making a static pdf, so don't feel this is urgent on my part. Still, for future projects it would be useful.
Cheers
