### ISSUE TITLE
Sozi 15.05 preview: No moving / rotating / ...

### ISSUE THREAD

**Issue by Moini** [senshu/Sozi#289]
Hi,
I've just downloaded the new preview version (Linux 64bit), unpacked it to my temp directory, and started it from a shell on Linux Mint 17.1.
It opens, and loads and shows my svg file, frames can be added and removed, but on the 'canvas', I cannot perform any actions, no matter if I select one of those buttons for the actions below or not.

The resulting animation (I then opted to only change the opacity, as that was the only thing I could change) does not show any animation (I expected the layer to become transparent, and then to show again), only the numbers in the top left corner change (and there's a strange ]> in front of them).

I then thought this might be related to the svg file itself, and opened and saved it with Inkscape 0.91. When I then opened the file with Sozi, the canvas stayed empty.

Both times, a frequent error message in the terminal is "TypeError: Cannot read property 'setAttribute' of undefined"

Did I miss some installation step or do you need more info?
Files from the first try (before passing through Inkscape 0.91) are here:
https://gist.github.com/Moini/bd19ed6ea52596da7c4b

And, btw., it would be good if there were some linebreaks in those files.
I had to try out several different graphical text editors to find one that wouldn't crash on them because of their line length... It wasn't fun to try copy-pasting them into the gist.

**Comment by senshu** [comment]
> I then thought this might be related to the svg file itself

Yes. It seems that the SVG produced by Adobe Illustrator is not compatible with Sozi. As far as I can see, it should be easy to fix.
I advertise Sozi as independent from any SVG editor but actually it is still biased towards Inkscape.

Could you please send me a simple SVG document with several layers? I need to see how Illustrator stores layer information.

> It wasn't fun to try copy-pasting them into the gist.

Maybe the gist is not the appropriate medium to share such files. I will see if I can insert some line breaks.

**Comment by senshu** [comment]
> I [...] opened and saved it with Inkscape 0.91.

When opening the file with Inkscape, did you choose the "SVG Adobe Illustrator (*.ai.svg)" format?
It seems you need to name your file with the extension ".ai.svg" to use this feature.

**Comment by Moini** [comment]
Sorry, I can't give you any AI files... 
As stated above the gist, I got that file from openclipart. I'm using Inkscape only for my own creations ;)
I can try the renaming this afternoon.

**Comment by Moini** [comment]
So it seems saving with Inkscape breaks the whole thing (no matter what name I choose, there's no picture in Sozi).
Just renaming the file and then using it with Sozi didn't help, either - no moving, etc. just like before.

Would this error message be a problem:
ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.

With a standard Inkscape svg it works pretty well, and is a lot easier to use than the extension - thank you! :D

**Comment by senshu** [comment]
This procedure worked for me:

1. Rename `lighthouse_01.svg` to `lighthouse_01.ai.svg`
2. Start Inkscape
3. File &rarr; Open.
4. In the Open dialog, select the file format "Adobe Illustrator SVG (*.ai.svg)"
5. Choose `lighthouse_01.ai.svg`
6. File &rarr; Save as &rarr; `lighthouse_01.ink.svg`
7. Start Sozi and open `lighthouse_01.ink.svg`

> Would this error message be a problem:
> ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox!

You can ignore this error message.

**Comment by Moini** [comment]
Thanks, that works.  :)
Now I found another problem - looks like an infinite loop while playing the animation in FF...
