### ISSUE TITLE
Sozi 13, linux - ImportError: No module named pygtk

### ISSUE THREAD

**Issue by joha1** [senshu/Sozi#291]
After a while of not using it, I wanted to start a presentation with sozi today.

However when trying to run sozi from the inkscape plugins folder, i get the following error-popup:

    Traceback (most recent call last):
      File "sozi.py", line 31, in <module>
        from sozi.ui import *
      File "/usr/share/inkscape/extensions/sozi/ui.py", line 18, in <module>
        import pygtk
    ImportError: No module named pygtk

So it cant find its gtk bindings, it seems?

Everything I can find regarding this error message, is about all the hoops you have to jump through to get it to run in windows, but I am on a linux system, with sozi, inkscape and python installed with the package manager, so that should not be able to happen.

Looking for `pygtk` with `yum search pygtk` only yields `pygtk2`, so maybe something changed here?

Another thing that comes to mind is that I have a second instance of python [(anaconda)](http://continuum.io/downloads) installed, [because of reasons...](http://pandas.pydata.org/), which differs from my system version, so that might be causing some confusion?

So did something break with pygtk2, or most I simply tell sozi by hand how to find pygtk? If so, how?

**Comment by senshu** [comment]
Did you install Sozi manually or did you install a package for your distribution?

**Comment by joha1** [comment]
I did install the package for my distribution.
Fedora 20 has  a package for sozi 13 in its repos, which used to work flawlessly at first.

**Comment by senshu** [comment]
> Looking for pygtk with yum search pygtk only yields pygtk2

I don't use Fedora, so I'm not aware of how packages are named there. In Ubuntu, the package is called `python-gtk2`.
In your case, did you actually install `pygtk2`?

I suppose that having several versions of Python installed can be a problem since each one will have access to its own set of packages. Unfortunately, I don't know how to force Inkscape to use the right one.

Also, please note that Sozi 13 is no longer maintained. Sozi 15 is still in a pre-release state but if you can tolerate a few minor bugs, it should be easier to install. However, I have tested it only in Ubuntu and I've got no feedback from Fedora users so far. You will find more information here http://sozi.baierouge.fr/release-15.05.html

**Comment by joha1** [comment]
>In your case, did you actually install pygtk2?

Yes, its installed. 

>I suppose that having several versions of Python installed can be a problem since each one will have access to its own set of packages. Unfortunately, I don't know how to force Inkscape to use the right one.

Yes, I guess that might be the culprit. So the problem probably lies with inkscape!? If I interpret you correctly, sozi just expects inkscape to be set up with python correctly, so there is no direct sozi-python interactions going on?

>Also, please note that Sozi 13 is no longer maintained. Sozi 15 is still in a pre-release state but if you can tolerate a few minor bugs, it should be easier to install. However, I have tested it only in Ubuntu and I've got no feedback from Fedora users so far. 

I tried 15, but there I ran into another problem (see my other post). Dont know if that is fedora related, or my personal I-dont-care-about-filesizes approach, but from my little "testing" I did so far, it seems to work OK.

**Comment by senshu** [comment]
> so there is no direct sozi-python interactions going on?

You're right. Python is launched by Inkscape. As far as I know, I cannot choose a specific version of Python to run Sozi.

> I tried 15, but there I ran into another problem

OK. Sorry for the confusion.

**Comment by senshu** [comment]
Sozi 13 is no longer supported. Closing this issue.
