### ISSUE TITLE
Presentation moving forward when clicking to start video

### ISSUE THREAD

**Issue by paalge** [senshu/Sozi#293]
This is a two part issue. 
First of all, the video doesn't autoplay when I embed it in inkscape.
This is not a hough issue, had it not been for the fact that when I press play, the presentation moves on to the next slide.
The xml code for the video is
```xml
<rect id="rect4189-3" height="768" width="1024" y="-2248.2227" x="5897.7207" style="fill:#aaaaaa;stroke:none">

    <ns1:video ns1:type="video/mp4" ns1:src="../Video/Omvisning/211214_DSLR.mp4" ns1:start-frame="9" ns1:stop-frame="10"></ns1:video>
</rect>
```

I'm using the latest from git, version 15.05.261817

**Comment by senshu** [comment]
> First of all, the video doesn't autoplay when I embed it in inkscape.

`start-frame` and `stop-frame` should be frame IDs, not frame numbers.

> when I press play, the presentation moves on to the next slide.

I will try to reproduce the issue.
Are you using the latest version the Sozi media extension from https://github.com/senshu/Sozi/releases/tag/15.05-preview ?

**Comment by paalge** [comment]
Thank you for the clarification.
With the frame IDs correct it starts automatically. Still changing anything in the video player moves the frame forward. I guess this is to do with the binding of left click to move to next slide?

**Comment by senshu** [comment]
> I guess this is to do with the binding of left click to move to next slide?

Yes, but the binding is supposed to be disabled on video elements.

> Should I switch to the preview?

No. Currently, preview and dev are identical.

**Comment by senshu** [comment]
Fixed. Check the [Sozi nightly builds](https://drive.google.com/open?id=0ByRUreHgekjMWG9teGM2dE8wck0&authuser=0) and install version 15.05.282127 or later.

Simply reopen your presentation in the Sozi editor. The HTML will be updated automatically.

**Comment by paalge** [comment]
Works, thank you.
