### ISSUE TITLE
Sozi 15 and layers ...

### ISSUE THREAD

**Issue by marcovth** [senshu/Sozi#294]
Hello ...

In InkScape, I have a background svg image with text as a new layer added to it.

The text is clearly visible on top of the background.

However in Sozi 15 the text layer is below the background image, and thus not visible.

Is there a way to rearrange that?

Unfortunately, it seems I can not upload a svg file.

**Comment by senshu** [comment]
> However in Sozi 15 the text layer is below the background image, and thus not visible.

How do you know that it is *below*?

> Unfortunately, it seems I can not upload a svg file.

Do you have an account to a cloud storage service like DropBox or Google Drive?

**Comment by marcovth** [comment]
Please try this link ...
https://www.dropbox.com/s/hak8861tuj23fhf/andre.svg?dl=0

**Comment by senshu** [comment]
Sozi assumes that all elements in your document belong to layers. This is how Inkscape is supposed to work as well: when you create a document, it already contains a default layer where your drawings and texts are supposed to go. Then you can add more layers if you want.

In your document, I see that the text is in the "Text" layer, but the drawings belong to no layer at all. It is not clear to me how you got this result.

I have modified your document, adding a background layer and moving all drawings there. Now it is displayed correctly in Sozi.
[Click here to download the modified version](https://drive.google.com/open?id=0ByRUreHgekjMejdsd1BQX29TZlk&authuser=0)

**Comment by senshu** [comment]
However, Sozi should have displayed your document correctly even if some elements were not in a layer. I have just pushed a fix for this bug.

**Comment by marcovth** [comment]
Thanks a lot. Good to know, thanks for the fix :)

I got the image from a scientific paper. More and more scientific papers require images to be delivered in vector format so that the pictures are better scalable for print. It's a nice source for Sozi presentations.

Merci.
