### ISSUE TITLE
Default layer visibility

### ISSUE THREAD

**Issue by beralt85** [senshu/Sozi#296]
**Context**:

According to inkscape, my [.svg file](https://beralt.pictor.uberspace.de/owncloud/public.php?service=files&t=e925ce38c0f9cc5c162834ab420c74af) contains only contains one layer.

**Actual behaviour**:
In Sozi 15 (e.g. Sozi-15.04.281146-linux64), when deactivating the visibility of the "default" layer, some objects vanish and others stay visible.

**Expected behaviour**:
The visibility of the Sozi default layer should be consistent, e.g. including all objects (on the first or all layers).

**Comment by senshu** [comment]
I have pushed a fix for this issue. You can try the latest nightly build from https://drive.google.com/open?id=0ByRUreHgekjMWG9teGM2dE8wck0&authuser=0
