### ISSUE TITLE
size object in inkscape and sozi

### ISSUE THREAD

**Issue by cotacot** [senshu/Sozi#297]
Sozi 15.05.142313 in ubuntu studio 14.04 and inkscape 0.91 (same issue with windows 7 , Sozi 15.05.142313 and inkscape 0.47)

When I draw an object as a separate layer in inkscape the object is relative to other objects smaller in sozi than in inkscape. I make the object in inkscape in the size that i want relative to the size of other objects. For instance I make an ellipse in layer 1 around a picture in layer 2. Loading the svg in sozi gives a smaller ellipse that i need to scale up in sozi to have it around the picture to get the same as in my inkscape file.
Maybe this is more a matter of knowing how to use sozi rather than a bug.

Nick

**Comment by senshu** [comment]
Can you provide a sample document to help me analyze the problem?

**Comment by cotacot** [comment]
Hello,

Unfortunately I could not reproduce the problems I encountered. I had 
them with the files in annex. The files might be messed up due to my 
learning curve of using sozi. So it could be that they are of no use to you.
I experiment further in the hope to give you a clear picture.
Please use files for your own need and do not distribute them. It is 
from a presentation I made for my job. I had a powerpoint with the same 
content a backup. But the sozi went well. My public was enthousiastic 
and asked what it is.
I still fuzzing with screen and projector resolution. And a tool to 
print handouts in pdf would be very useful.

Nick

**Comment by senshu** [comment]
> Please use files for your own need and do not distribute them

This conversation is public: my message and your answer are part of the thread that you opened in the GitHub issue page for Sozi.
Fortunately for you, GitHub discarded the attachments.
Unfortunately, I did not receive them either.

**Comment by cotacot** [comment]
Cher Guillaume,

Ou est-ce-que je peut envoyer les fichiers sans les avoir disponible 
pour tout le monde ?

Nick

**Comment by master-bit** [comment]
I got the same problem. But only sometimes. Seems pretty unpredictable. Also (sometimes) I have got a presenatation running, everything in place. Then I want to change something, reopen it in Sozi and suddenly the layer have all changes size relatively. I cannot really reproduce this since it occurs quite irregularly (at least I did not find out when it happens exactly yet)

**Comment by senshu** [comment]
This issue is 3 years old and no additional info was provided to help me reproduce the problem. Closing.
