### ISSUE TITLE
Independant Layers and their visibility per view

### ISSUE THREAD

**Issue by neko-jump** [senshu/Sozi#298]
Hello,

I'm a mere user and as i 'm facing some bug i just report it.

I tried the "first presentation" files both on online and desktop version, and i have the same bug.
first i add a layer with a star with inkscape, save it, then open it in sozi.

what happen is that first the layer of the star do not move with the background. if i zoom, the layer do not move while the background does.
then when i create a new frame, the star moves randomly, and even once became very small.

original picture on inkscape:
![capture d ecran - 19062015 - 11 05 47](https://cloud.githubusercontent.com/assets/12964522/8250383/672b684e-1673-11e5-9878-1dbcfaa87700.png)

then first:
![capture d ecran - 19062015 - 11 04 14](https://cloud.githubusercontent.com/assets/12964522/8250386/7248f444-1673-11e5-8d69-cbbb6d5d9d8b.png)

second:
![capture d ecran - 19062015 - 11 04 48](https://cloud.githubusercontent.com/assets/12964522/8250389/7a02d970-1673-11e5-9030-34e18514d30d.png)

we can see that the star do not correspond in the 2 frame to the same position.

By the way, it is very important to me to have the possibility to make a presentation by showing different layers.
For example to show a map, then adding text on it on a second frame.
I think it is possible to do it with sozi but it is not very clear. I suggest to add an option of showing layer for each frame, instead of showing a layer for the full sequence. I think this would be more clear to work with.

![capture d ecran - 19062015 - 11 13 00](https://cloud.githubusercontent.com/assets/12964522/8250598/9edc3d20-1675-11e5-9dbe-d8222e6d1336.png)

**Comment by senshu** [comment]
> what happen is that first the layer of the star do not move with the background. if i zoom, the layer do not move while the background does.

Are you sure that the star belongs to the layer ETOILE?
Can you send me the document to help me analyze the issue?

> I suggest to add an option of showing layer for each frame, instead of showing a layer for the full sequence. I think this would be more clear to work with.

I suppose that this is not directly related to the problem you described. Maybe you should open another issue for this.
Please explain in detail the role of the buttons when they are applied to a specific frame. At the moment, I don't understand how it is supposed to work.

**Comment by neko-jump** [comment]
1_ ok, how can i send you the file?
yes the star belongs to the layer ETOILE.

2_ ok let's take an exemple:
first i would have to show an itinerary: 
![capture d ecran - 19062015 - 16 49 41](https://cloud.githubusercontent.com/assets/12964522/8255861/4dc69970-16a3-11e5-9837-32167c2a4080.png)
 
then i want to show the full map:
![capture d ecran - 19062015 - 16 53 05](https://cloud.githubusercontent.com/assets/12964522/8255927/b26947ec-16a3-11e5-8900-c2890c3b36f2.png)

and then i want to make appear successively:
![capture d ecran - 19062015 - 16 54 31](https://cloud.githubusercontent.com/assets/12964522/8255953/e1769a1c-16a3-11e5-96c4-9af3481aa59f.png)
a house...
![capture d ecran - 19062015 - 16 55 21](https://cloud.githubusercontent.com/assets/12964522/8255975/00b16920-16a4-11e5-99b6-32aee0f65bcc.png)
and a name. 

so here i use 3 layer and i need them to do not appear at the same time for my presentation, while my document is:
![capture d ecran - 19062015 - 16 57 06](https://cloud.githubusercontent.com/assets/12964522/8256009/4a8d20ac-16a4-11e5-9ebb-3659c0579dda.png)

**Comment by neko-jump** [comment]
si jamais je rajoute ce détail:
![capture d ecran - 19062015 - 16 58 47](https://cloud.githubusercontent.com/assets/12964522/8256031/7ae5855a-16a4-11e5-99b8-413f49c0f663.png)

**Comment by neko-jump** [comment]
well now, i even cannot visualize the different layer in sozi...
![capture d ecran - 19062015 - 17 20 06](https://cloud.githubusercontent.com/assets/12964522/8256518/dc31f430-16a7-11e5-8d32-4219e0ddaca5.png)

**Comment by senshu** [comment]
> how can i send you the file?

The easiest would be to use a cloud file sharing service like DropBox or Google Drive.
Some users paste their SVG and JSON files to https://gist.github.com/

**Comment by neko-jump** [comment]
so it would be something like this, where the layer
par défaut => the back ground ogf the map
num 1-5=>  the layer where there is the 5 spots to show successively.

![capture d ecran - 19062015 - 17 36 28](https://cloud.githubusercontent.com/assets/12964522/8256840/f7930d7a-16a9-11e5-8728-17299c8d4632.png)

mmm so i beg here is the link:https://gist.github.com/8a5a173407f4d93850d6.git

**Comment by senshu** [comment]
1. As far as I can see, the map in the background does not belong to any layer of your document. This is known to cause problems in the official Sozi 15.05 preview release.
2. If you want to make a layer appear or disappear, you should modify the layer opacity (opacité du calque) in the desired frames.

**Comment by senshu** [comment]
[I have made a sample presentation](https://drive.google.com/folderview?id=0ByRUreHgekjMfnJ5Z0xpb3ZfNG1ZUGQ0ZHhmRTloSndGSjgwUEoxaEEyTDR5aEhEY0ZwNHM&usp=sharing) using your `exemple.svg` document.

I have used the latest build from the [Sozi-nightly shared folder](https://drive.google.com/open?id=0ByRUreHgekjMWG9teGM2dE8wck0&authuser=0). I suggest that you install it in place of the official Sozi 15.05 as it may solve your issues with layers.

**Comment by neko-jump** [comment]
woaw great! that's what i want!
i believe the latest is the 15.06 - 10.21.35, i'll try this one!

**Comment by neko-jump** [comment]
ok i understood.
when we zoom, it zoom only the layer selected, when i use the scroll wheel.
i cannot use the option Alt+ mouse because on my Os this is already an option for the window use:
alt+ left button clic= move the window
alt+ scroll roll = change opacity of the window.

so now i understood we must select all the layer for it to work. so this wasn't a bug.

i had been very surprised by the 3 button near " id de l'élément de référence" !
is there an option to cancel the lasts actions?

**Comment by neko-jump** [comment]
One more word to say that to actualise the sozi presentation when we changed the .svg do not work perfectly. i did have to save the document by "save as"... replace... in order that it works.

**Comment by Oximore** [comment]
Hi,

I do not found very intuitive to put opacity of a layer to 0 if we want hide it.
It may be implement like that but it should be an option to hide a particular layer for a particular frame.
I found this suggestion quite good : 

![boxes by layers and frames](https://cloud.githubusercontent.com/assets/12964522/8256840/f7930d7a-16a9-11e5-8728-17299c8d4632.png)

I understand this picture like this : for each frame and each layer you can quickly decide if you want to display it or no.

I do not suggest to remove opacity functionality, but help the user by adding a "shortcut" to put opacity to 0%.

Sincerly,
Benjamin.

Ps: Thanks for this beautiful open software :)

**Comment by senshu** [comment]
@Oximore In the current interface, the *timeline* pane (at the bottom) is used for selecting frames and reordering them. The *properties* pane (on the right) is used for editing the selected frames.

I don't like the idea of adding edition features directly in the timeline. I could add shortcuts to set the opacity to 0% or 100%, but I would put them next to the current opacity control, in the properties pane.
