### ISSUE TITLE
Adding layers to an SVG document for an existing Sozi presentation

### ISSUE THREAD

**Issue by senshu** [senshu/Sozi#300]
Steps to reproduce:
1. Create an SVG document.
2. Open it with the presentation editor.
3. In the presentation editor, move the camera for the default layer.
3. In the SVG editor, add a new layer containing some drawing elements.
4. In the presentation editor, the document is automatically updated.

Observed result: the new layer is part of the _Default_ layer set, but its camera is not in sync with the other _Default_ layers.

Expected result: the camera of the new layer should have the same properties as the other cameras in _Default_.

**Comment by clement-moulin-frier** [comment]
Hi @senshu 

Do you still plan to solve this issue? 
From my personal experience with Sozi, it is the only major problem I have with the software. All the rest works very well.

Thanks,
Clément

**Comment by senshu** [comment]
> Do you still plan to solve this issue?

Yes. As soon as I can.

**Comment by senshu** [comment]
You can try Sozi 16.11, available in the [Sozi nightly builds](https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0?usp=sharing)
