### ISSUE TITLE
The Problem of Converting the svg ro pdf. The loss of Greek letters

### ISSUE THREAD

**Issue by isaxs** [senshu/Sozi#302]
Dear Senshu,
I found a bug in the converting the svg to pdf. The greek letters can't be converted in correct format. The original file is attached here. https://drive.google.com/open?id=0B8wyGaILXrI7QTNWRDMwVkQ4Y00&authuser=0
The Qrela.eps is generated by the software xmgrace which is a quite common curve-plot software. When I show the Q_sozi.svg in the googlechrome, there is no problem. The convert problem only happens in the pdf. How do you solve this problem, I really want to keep the scale-vector format of the Qrela.eps in the Q_sozi.svg file.
p.s. 
I can convert the Qrela.eps to Qrela.png, but I lose the scale-vector format. The display effects are not good anymore. This is a solution I can make currently, obviously it's not the final solution.

**Comment by senshu** [comment]
Thanks for this report.
PDF export has not been ported to Sozi 15 yet. I will take this issue into account when I start working on it again.

**Comment by isaxs** [comment]
Thanks. This problem exists in the version 13.11 as well.

**Comment by ejvindh** [comment]
The problem is solved if you do an "Object to path" on the entire document before dragging it through sozi2pdf.

**Comment by isaxs** [comment]
Thank you very much. Your solution is easy and workable.

**Comment by senshu** [comment]
sozi2pdf has been moved to a separate project: https://github.com/senshu/Sozi-export
