### ISSUE TITLE
Is a statically linked Linux 64-bit version possible?

### ISSUE THREAD

**Issue by akahlich** [senshu/Sozi#309]
First of all, this is a wonderful application. I do have the 15.05 preview running on a Windows 7 laptop of mine. No problems encountered so far, but I have not used it extensively yet.

I do most of my work on my desktop, which runs 64-bit CentOS 6.6, so I would like very much to run Sozi on that machine.

A download and "install" of the Sozi-15.05.142313-linux64.tgz on a CentOS 6.6 system yields:

% ./Sozi 
./Sozi: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory

After "fixing" that, I get:

% ./Sozi 
./Sozi: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./Sozi)
./Sozi: /usr/lib64/libstdc++.so.6: version`GLIBCXX_3.4.15' not found (required by ./Sozi)

I can and likely will download the source for those, build and install them - but not everybody knows how to do that. I also don't know what other dependencies I will not have after those are satisfied.

I also tried downloading the source and following the build instructions, but they are for more recent Linux distributions, so I had trouble getting the dependencies to be resolved. At least, they did not resolve automatically.

Other potential users may have the same problems, so I suggest the usual solution to this type of problem: provide a statically linked version. Yes, it will be much bigger, but it may also end up eliminating some support requests while making this application available to a broader range of users - not all of whom want to run on the "latest, greatest" Linux distribution but want stability instead.

My attempt at downloading the source and building the application was to try to help supply a statically linked build but no joy yet. The Sozi build process I saw would be a long learning process for me.

**Comment by senshu** [comment]
Sozi runs on top of a web browser engine called [NW.js](http://nwjs.io/). All Sozi releases are based on the official binaries of NW.js. Unfortunately, these binaries do not support "old" versions of glibc.

> My attempt at downloading the source and building the application was to try to help supply a statically linked build

Rebuilding Sozi alone will not help. You would need to rebuild NW.js as well. I have never tried that.

> Other potential users may have the same problems

I understand your concern and I agree with your proposed solution. I will keep this issue open but I cannot promise anything in the near future.

I would be glad if someone could help me solve this issue. The time I can spend on Sozi is limited and there are already many things to do.

**Comment by bashiri** [comment]
I downloaded Sozi-15.05.142313 desktop application for Windows. But I do not how to install it. When I am running it just a window without menu or option approved. Would you please guide me how to install and use it in windows? 
Of course I tried Sozi on Inscape but as you have written in your blog it has problems with Python and other extensions. So after one week I could not access to Sozi environment.

**Comment by senshu** [comment]
@bashiri You are supposed to run the Sozi executable. A window should open and propose to open an existing SVG document.

As far as I can tell, your problem is not related to the original question (Is a statically linked Linux 64-bit version possible?) Can you please open a new issue?

**Comment by senshu** [comment]
@bashiri By the way, the latest stable version is [Sozi 15.11](http://sozi.baierouge.fr/release-15.11.html). Is there a particular reason why you downloaded version 15.05?

**Comment by senshu** [comment]
@akahlich I have published a new non-official version here: https://drive.google.com/folderview?id=0ByRUreHgekjMWG9teGM2dE8wck0&usp=sharing#list

Can you please tell me if it has the same issue?

**Comment by akahlich** [comment]
Hi,

I tried it on Centos 6 and this is what I got:

art@kade1:~/dev/Sozi-16.06.152156-linux-x64>./Sozi
./Sozi: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found 
(required by ./Sozi)
./Sozi: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found 
(required by ./Sozi)
./Sozi: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found 
(required by ./Sozi)
./Sozi: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found 
(required by /home/art/dev/Sozi-16.06.152156-linux-x64/libnode.so)
art@kade1:~/dev/Sozi-16.06.152156-linux-x64>

It appears to be hardwired to expect a more current version at 
/usr/lib64/libstdc++.so.6

Thanks for the try. If I wasn't so busy with trying to design hardware I 
would try working my way through a static build myself - messy though it 
may be.

Cheers,
Art

On 06/16/2016 12:31 PM, Guillaume Savaton wrote:
>
> @akahlich <https://github.com/akahlich> I have published a new 
> non-official version here: 
> https://drive.google.com/folderview?id=0ByRUreHgekjMWG9teGM2dE8wck0&usp=sharing#list
>
> Can you please tell me if it has the same issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/senshu/Sozi/issues/309#issuecomment-226589040>, or 
> mute the thread 
> <https://github.com/notifications/unsubscribe/ACk2X7pJinqXTmcRuVrgi9TCsYRGhSS5ks5qMaR2gaJpZM4FbaHX>.
>


-- 
Arthur Kahlich
1220 Vienna Dr #476
Sunnyvale, CA 94089
Phone: (408)734-8870
