### ISSUE TITLE
PhantomJS - phantom.args to system.args - please change it

### ISSUE THREAD

**Issue by nedab** [senshu/Sozi#310]
Hello,

with the new PhantomJS 2.0 I ran into an error with args.
So I changed the sozi2video.js and worked it over to system.args but I am missing the knowledge to debug it.

What I did, and I seems to work, is this:

AT THE TOP ADDED:
 
     var system = require('system');

CHANGED THE NUMBERS FOR THE ARRAY:

       if (system.args.length < 4) {
    console.log("Usage: sozi2video.js url.svg dir width_px height_px");
    phantom.exit();
        }
      else {
       page.viewportSize = {
        width: parseFloat(system.args[3]),
        height: parseFloat(system.args[4])
       };

    page.onInitialized = function () {
        page.evaluate(function (main, options) {
            main(options);
        }, main);
    };
    
    url = system.args[1];    
    tmpDir = system.args[2] + "/";

**Comment by senshu** [comment]
sozi2video has been moved to [a separate project](https://github.com/senshu/Sozi-export).
The new implementation supports only presentations made with Sozi 15. It is based on SlimerJS [and still uses phantom.args](https://docs.slimerjs.org/current/api/phantom.html).

Sozi 13 is no longer maintained. This issue will not be fixed.
