### ISSUE TITLE
Running Problems

### ISSUE THREAD

**Issue by lfigueredo** [senshu/Sozi#311]
Hi,

I've tried for the first time the Sozi15 64bits for linux, but I've got the following error as soon as I runned it 

"[8303:0722/224739:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on."

I haven't installed the dependencies before running (It would probably be a good idea to link the git readme to the website download page such that anyone knows the required dependencies.  =).

Still, I  was not able to use the new Sozi. I had the same SUID sandbox issue.
Hence, I decided to build Sozi from source. I used the README install guide which is pretty good. Still, I had to do the following 
1)  sudo apt-get install nodejs npm (missed the npm package)
2) Using bower, you may get the following error
"usr/bin/env: node: No such file or directory"
This hapends because other linux distros install node js into /usr/bin/node, and you have to do in order to fix this is to create a symlink: (see, http://www.smartinfoblog.com/how-to-install-bower-on-ubuntu/)
ln -s /usr/bin/nodejs /usr/bin/node  
3) bower is not allowed to run as sudo, but it has permission issues. To avoid then, use 
sudo bower --allow-root install

The new Sozi has been build succesfully, but when trying to run  Sozi  in 64bits for linux, I've got the same error message about the SUID sandbox. 

Do you know how I can solve or bypass this issue? 
I'm not quite sure how important is the SUIDSandbox issue, but I've also got the following error which I think is indeed a big deal  :/

[5780:0723/121038:ERROR:nw_shell.cc(335)] TypeError: Cannot read property 'root' of undefined
    at d.Object.defineProperty.get (file:///tmp/.org.chromium.Chromium.ejJGGi/js/editor.min.js:3:9622)
    at d.l.repaint (file:///tmp/.org.chromium.Chromium.ejJGGi/js/editor.min.js:3:14212)
    at Object.e.onMouseEnter (file:///tmp/.org.chromium.Chromium.ejJGGi/js/editor.min.js:3:23170)
[5780:0723/121038:INFO:CONSOLE(3)] "Uncaught TypeError: Cannot read property 'root' of undefined", source: file:///tmp/.org.chromium.Chromium.ejJGGi/js/editor.min.js (3)

**Comment by senshu** [comment]
Sozi runs on top of a web browser engine called [NW.js](http://nwjs.io/) (formerly node-webkit). The SUID sandbox error is displayed when running the NW.js executable.
When you rebuild Sozi from source using the provided instructions, only the JavaScript application is rebuilt. The building process still pulls the official binaries of NW.js.

> Do you know how I can solve or bypass this issue?

I have the same message every time I run Sozi.
As far as I can tell, it does not prevent the application from running correctly.

The other messages could be the reason why it does not run. I'll get back to you to have more details.

**Comment by lfigueredo** [comment]
Hi! Thank you for clearing the SUID Sandbox issue up for me!  =)

If you need any help with the other messages, I'm tying to run the Sozi-15.07.222238-linux64 at an Ubuntu 14.04 (64bits, Kernel 3.13.0-48). 
Is there any log file that I could send you? I've found in the config files that the links for SingletonCookie and SingletonLock are pointing to nowhere
SingletonCookie -> 7088179181768778722
SingletonLock -> replicant-8204
(replicant is the computer name)
I don't think this is related but if it helps...

**Comment by senshu** [comment]
Sozi is no longer based on node-webkit. I will close this issue. Feel free to report a new issue if you still have this problem with the current stable version.
