### ISSUE TITLE
Browser: Videos in Sozi 15 are only working for Firefox

### ISSUE THREAD

**Issue by umut885** [senshu/Sozi#312]
If you insert a Video in Sozi 15, as described for Sozi 14 in Issue #243 it only runs perfectly for Firefox.
Other browsers show the video in the upper left corner.

Is it possible to fix that?

First picture: Firexfox - Video is in correct position. Video is playing.
Second picture: Any other browser - Video in wrong position. Video is not working.

![firefox](https://cloud.githubusercontent.com/assets/13699261/9150084/736f6048-3dc8-11e5-89bb-2f7118580c9c.jpg)
![other browsers](https://cloud.githubusercontent.com/assets/13699261/9150085/78044c9a-3dc8-11e5-8399-c1ea4c0998a9.jpg)

**Comment by senshu** [comment]
There is already a warning about this in the website of Sozi:
http://sozi.baierouge.fr/pages/tutorial-media.html

> Currently, Chrome (as of version 33) does not apply geometrical transformations (rotation, scaling, translation) to video elements embedded in SVG documents. Videos will always show in the top-left corner of the browser window. As far as we know, only Firefox handles videos correctly.

This is a bug in web browsers, not in Sozi.
