### ISSUE TITLE
player ignores #frameNumber in shared URL

### ISSUE THREAD

**Issue by sunaku** [senshu/Sozi#315]
Hello,

I'm using Sozi-15.06.302155 where the `#frameNumber` in the URL is not being respected when the page loads.  For example, when I share the URL of a particular frame with others, they are _always_ taken to the _very first_ frame in the presentation instead! :scream: This bug makes it difficult to share information with others.

Thanks for your consideration.

**Comment by senshu** [comment]
I cannot reproduce the bug. URLs with frame numbers work correctly in my tests.
Can you provide a sample document that illustrates the issue?

**Comment by sunaku** [comment]
Sure, here are the sample files:
https://gist.github.com/sunaku/e96cb55023f282eed71b

After you download them:
1. open the HTML file in your browser
2. press the right arrow key to go to the second frame (spiral)
3. copy the browser URL
4. open a brand new browser window
5. paste the copied URL
6. observe the bug

I am able to reproduce this bug under Firefox 40.0.3. :fire:
