### ISSUE TITLE
Small typo in README.MD

### ISSUE THREAD

**Issue by JurgenG** [senshu/Sozi#319]
Hi,

in the README.MD file, there's dependencies that need to be met. You'll need to install Node.js
The apt-get file to install is _node.js_, and not nodejs.

**Comment by senshu** [comment]
Which distribution are you using? As far as I can see, in Debian and Ubuntu, the package name is "nodejs".
http://packages.ubuntu.com/search?keywords=nodejs&searchon=names&suite=all&section=all
https://packages.debian.org/search?keywords=nodejs&searchon=names&suite=all&section=all

Or maybe you are using an alternative repository where the package has another name.

**Comment by jristz** [comment]
In Arch Linux, Antergos, Manjaro and is nodejs if I'm right
