### ISSUE TITLE
Can't "save presentation" using Sozi 15.06 on Windows with Inkscape

### ISSUE THREAD

**Issue by GitHofi** [senshu/Sozi#320]
Hi
I really like Sozi and especially version 15. Unfortunately I can't save changes.

Sometimes I can save once (and the info text appears in the right upper corner) but most of the time hitting the save button ![2015-09-30 14_32_32-right arrow](https://cloud.githubusercontent.com/assets/12327228/10192947/3ffbfa0a-6780-11e5-98de-3f7f0382fa6e.png)  just does nothing

In this state I also can't close Sozi - I have to kill the process using taskmanager BUT I can still work within Sozi (change settings).

I tried the win32 and the win64 version of Sozi and I tried Sozi on Windows 7 and Windows 8.1.
-> the problem was always the same.

Maybe it has something to do with the svg file I created using Inksape (v0.91)?

I hope you can find and fix this problem.

Greetings from Vienna
Sven

**Comment by GitHofi** [comment]
2 additional infos:

**1) works with gDrive**
I uploaded the files to gDrive and there it can be saved without problems.

**2) works locally with other presentations**
I just created a different presentation (using a Mindly mindmap -> exported to PDF -> imported in Inkscape -> used it in Sozi). Although this looks like a complex scenario it is working - I can save the presentation without problems.

I hope this helps to find the cause of this problem.

**Comment by senshu** [comment]
So, if I understand both scenarios,

* with a hand-made SVG, Sozi fails to save the presentation,
* with an SVG generated from a PDF, saving works.

It seems that the bug is related to the content of your original SVG document.
I will need to look at your document to reproduce the problem. Can you send it to me via a file-sharing service or using https://gist.github.com/ ?

**Comment by GitHofi** [comment]
Thanks for having a look at it.

Yes, that's right - the strange thing is that the same hand-made SVG works if I upload it to gDrive.

You can download the problematic SVG from my dropbox:
https://dl.dropboxusercontent.com/u/7889007/tempSharedFiles/Scrum-2015-10-06.zip

**Comment by lioman** [comment]
I've got the same problem under Ubuntu/Linux 15.10 64bit. There is this error on the console:
`"Uncaught TypeError: undefined is not a function", source: file:///tmp/.org.chromium.Chromium.RU0Peo/js/editor.min.js (2)`

**Comment by senshu** [comment]
I could reproduce the issue with the document from @GitHofi 
Sorry for not coming back on this earlier.

The error happens when Sozi attempts to set the spiral as the reference element of the current frame. I don't know why at the moment.

**Comment by senshu** [comment]
This issue has been fixed in Sozi 15.11. See the [nightly builds](https://drive.google.com/open?id=0ByRUreHgekjMWG9teGM2dE8wck0) until it is officially released.
Feel free to reopen this issue if it still does not work for you.

**Comment by GitHofi** [comment]
I can confirm, that the problem was solved.
THANKS :-)
