### ISSUE TITLE
Fit to reference object no longer supports rotations

### ISSUE THREAD

**Issue by kdesnos** [senshu/Sozi#321]
When fitting the view to a selected object in Sozi, the "horizontal" rectangle containing the selected element is used without any rotation.
In previous Sozi version, there was an automated rotation of the camera to fit, for example, a tilted rectangle. Getting this feature back would be nice when using frames to configure camera movements.

**Comment by senshu** [comment]
> In previous Sozi version, there was an automated rotation of the camera to fit, for example, a tilted rectangle.

I could not reproduce the issue. Fitting to a rotated rectangle works correctly for me. If you confirm that you still have this problem, can you please send me a sample document?

**Comment by kdesnos** [comment]
Hi,

Yes, I confirm that I still have this issue.
Enclosed to this answer is an example sozi project illustrating the issue.
It contains an image, and two rectangles.
When trying to fit rectangle with id "1", sozi fails to apply any 
rotation (with Sozi 15.06).

(Otherwise, the tool works great and produces amazing results :) ).

**Comment by senshu** [comment]
> Enclosed to this answer is an example sozi project illustrating the issue.

When you send a message to the GitHub issue tracker, attachments are removed.
I suggest to use a file sharing service like DropBox or Google Drive. Some people also use https://gist.github.com/ for this purpose.

**Comment by kdesnos** [comment]
Oops, sorry about that.
Here is the link: https://gist.github.com/kdesnos/c73ebb3da9475bea4bd8

**Comment by senshu** [comment]
@kdesnos In your document, the shape with id "1" looks like a rotated *rectangle* but it is actually a *path*.

When a path is rotated in Inkscape, the coordinates of its vertices are updated. In the SVG document, there is no clear indication that the shape has been rotated and Sozi does not make any assumption about it. I would suggest to use real rectangles to delimit your frames, or take care to avoid converting them to paths.

In the past, there was a feature request about being able to *recognize* a rectangle from a path but I declined to implement it.
