### ISSUE TITLE
Install guidelines for version 15

### ISSUE THREAD

**Issue by Globulle** [senshu/Sozi#327]
Hi,

I used an old version of Sozi one year ago and I really liked it, but I don't know how to reinstall the last version on my new computer (Kubuntu 15.10). Could you give some guidelines to install it properly?

Thank you very much.

**Comment by senshu** [comment]
I have just updated the installation instructions.
http://sozi.baierouge.fr/pages/20-install.html

**Comment by Globulle** [comment]
Thank you! This is indeed very simple, but I was not expecting the fact it runs outside Inkscape! :-)
