### ISSUE TITLE
Broken sozi2pdf

### ISSUE THREAD

**Issue by jeanparpaillon** [senshu/Sozi#328]
Hi,
sozi2pdf included in master is broken:

$ ./sozi2pdf.py /path/to/presentation.sozi.html 
sozi2pdf.js> Error: Problem parsing d=""
sozi2pdf.js> Error: Problem parsing d=""
sozi2pdf.js> Your document must include Sozi version 12.09 or above.
TypeError: 'undefined' is not a function (evaluating 'this.onDrag.bind(this)')

**Comment by senshu** [comment]
sozi2pdf has not been updated for Sozi 15. It is still in the master branch but is not compatible with the current file format.

**Comment by senshu** [comment]
PDF and video export tools are now available for Sozi 15.
They belong to a separate repository: [Sozi-export](https://github.com/senshu/Sozi-export).
