### ISSUE TITLE
Non-standard fonts are not displayed correctly

### ISSUE THREAD

**Issue by senshu** [senshu/Sozi#329]
This issue has been reported for Sozi in Windows with the Futura Normal Condensed font.

**Comment by christiangedge** [comment]
I have produced a diagram in Inkscape and used a font called Futura-normal Condensed.  It does not come standard with Windows, but is a smart sans serif font similar to Arial, and reasonably well known.  When I load up my file on Sozi, it replaces my text with a completely different serif style font.

When viewed on the internet, Firefox and Chrome also behave as described.  Edge retains the Futura font but all of the spacing is lost.

**Comment by master-bit** [comment]
Maybe you can try to convert your text elements to paths in the svg file..

**Comment by senshu** [comment]
@christiangedge I have published a new non-official version here: https://drive.google.com/folderview?id=0ByRUreHgekjMWG9teGM2dE8wck0&usp=sharing#list

Can you please tell me if it has the same issue?

**Comment by senshu** [comment]
@christiangedge I will consider this issue as closed. Please feel free to reopen it if you think it is not solved.
