### ISSUE TITLE
Appear/Disappear Objects

### ISSUE THREAD

**Issue by assemblywizard** [senshu/Sozi#33]
First of all: great code!

I would find VERY useful if would be possible to make some object appear/disappear during the view flow or in between two views, i.e. allow to change dynamically the visibility parameter.

Thanks!

**Comment by senshu** [comment]
In Sozi 15, layer opacity allows to achieve a similar effect as showing/hiding objects.
Please try Sozi 15 and open a new issue if you think that your problem still deserves to be addressed.
