### ISSUE TITLE
Add icon to installation folder

### ISSUE THREAD

**Issue by senshu** [senshu/Sozi#330]
It will help create launchers for Sozi (eg .desktop file for Linux).

**Comment by zsteinmetz** [comment]
What about something like this (inspired by [Numix Circle](https://github.com/numixproject/numix-icon-theme-circle))?

![sozi](https://cloud.githubusercontent.com/assets/10266826/12537872/f1b476be-c2ca-11e5-96f0-f84c12a2921e.png)
