### ISSUE TITLE
Sozi 15 slow on big SVGs (1.8M)

### ISSUE THREAD

**Issue by ka-ba** [senshu/Sozi#337]
On a big poster (svg, A1, 1.8MB, 52 objects) unfortunately Sozi 15 is quite slow. Reaction on moving, scaling or rotating a frame can take 5 to 10 seconds.
Sozi version is the stable 15 as downloadable today, linux 32
the laptop is not too old (Intel i3 M380 2.53GHz)

I love sozi and I'd love to see it optimized in speed.

**Comment by roggan87** [comment]
I also had troubles with the rendering being slow, but [this tutorial](http://sozi.baierouge.fr/pages/tutorial-performance.html) helped me *a lot*! Especially converting texts to paths makes a big difference, Also make sure not to use overly high-definition bitmap images scaled down in the svg.

**Comment by senshu** [comment]
This issue has been open for more than 3 years. Since the bug report does not provide a scenario to reproduce the problem, I don't know whether it is still an issue in recent versions of Sozi.

Feel free to reopen it.
