### ISSUE TITLE
Sozi 15 Add button for setting the slide to "default" view.

### ISSUE THREAD

**Issue by dextras** [senshu/Sozi#338]
First of all: Sozi is a great project and i hope it will continue its development ;)

I was trying to add some animation to the presentation I am preparing but currently it is still quite troublesome, as you need to have several(or tens) layers for each step in the animation. The effect is quite amazing though ;)

The problem arises when in the proceeding "view/slide" you want to go back to the original placement and size of the layers (assuming they were resized/moved earlier). Currently I do not see an option to go back to such a "default" or "original" view.

**Comment by roggan87** [comment]
It would be very handy to be able to set the rotation angle, zoom and x/y-position manually. That way one could easily "reset" frames.

Right now one can work around this issue by duplicating an earlier frame, unlink it and move it. That way everything is reset to an earlier state. If you don't want to reset all layers you can relink the specific layer afterwards that you don't want to reset. It's not a perfect solution but it works in many cases.
