### ISSUE TITLE
ERROR:browser_main_loop.cc and ERROR:nw_shell.cc ........

### ISSUE THREAD

**Issue by Defossez** [senshu/Sozi#346]
Hi,

When starting Sozi in a terminal the Sozi tool starts but the terminal window shows a list of errors.#
The first displayed error is: ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox!
That one seems because I don't have a google tool installed and I've seen it with other tools too.
The second error is: ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'root' of undefined
This error pops up with every button or other I use in Sozi.

Can somebody tell what this is?

Each of the error messages complains about a file in the /tmp directory.
         "Uncaught TypeError: Cannot read property 'root' of undefined", source: file:///tmp  /.org.chromium.Chromium.Bm83b3/js/editor.min.js (4)

I checked and that file exist, but I don't know what's wrong with it.

Thanks.

**Comment by senshu** [comment]
I have published a new non-official version here: https://drive.google.com/folderview?id=0ByRUreHgekjMWG9teGM2dE8wck0&usp=sharing#list

Can you please tell me if it has the same issue?

**Comment by bronger** [comment]
It does not have these issues.
