### ISSUE TITLE
Hiding the video controls

### ISSUE THREAD

**Issue by Benjou** [senshu/Sozi#347]
Because the start and stops of videos are controlled by sozi anyways, I wanted to get rid of the controls, which take away some precious space on the screen.

I found a way to achieve this:

In a text editor, I open the *.sozi.html file and search for
`
h.setAttribute("controls","controls")
`
If I delete this string, controls are gone, movies are gorgeous.
Could there be a way to have this, either optional or by default, without having to hack into the html code manually?
That would be awesome.

**Comment by pierrethibault** [comment]
+1 I'd like to see this as well!

**Comment by andyofmelbourne** [comment]
+1 for me also!

I use Sozi for a lot of my scientific presentations and there are often a lot of movies to present.

**Comment by senshu** [comment]
I have pushed a modification that hides the media controls by default.
A new option is available in the Inkscape extension to enable them.

This feature will be part of the next release. I will upload the current development version to the [Sozi nightly shared folder](https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0) soon. Look for version 18.11.04 or above.
All you need to do is re-open your presentations with Sozi and let it save them automatically.
