### ISSUE TITLE
Audio or video didn't auto start

### ISSUE THREAD

**Issue by magicvince** [senshu/Sozi#350]
Hi, 

Input a video or an audio components via inkscape, I specify the id of the starting frame but nothing happen (and if i start manually my the media file, the stop frame doesn't work too).

(using sozie 1602 with mint debian (jessie))

**Comment by senshu** [comment]
Can you provide a sample document that could help us reproduce the issue?

**Comment by magicvince** [comment]
I try to clean my bad file... and I found error in my original svg (the id of the starting and ending frame weren't updated) I correct it with inkscape XML editor and it work. 
So, my apologize, this issue seems to be resolved.
Thanks
