### ISSUE TITLE
Frame title not updated is moving slide

### ISSUE THREAD

**Issue by vgstef** [senshu/Sozi#351]
With Sozi 16, if we follow this sequence, the title frame isn't updated : 
1. Click on a frame
2. Add some letters to the title frame (don't press Enter)
3. Move the slide
4. Click on an other frame

Expected behavior is to have the title frame updated, without the need to press Enter. 
If instead of moving the slide we click in the Id field, the title is updated. Probably just a "focus lost" not triggered when clicking inside the slide viewer.

**Comment by senshu** [comment]
Fix available in the nightly builds (Sozi 17.05.201844) https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0?usp=sharing
