### ISSUE TITLE
Sozi Hussled Fonts

### ISSUE THREAD

**Issue by tvld** [senshu/Sozi#352]
16.02 running on Ubuntu 14.04 shows hussled fonts. In Inkscape & Firefox they show ok.

![sozi-font-bug](https://cloud.githubusercontent.com/assets/986182/13492125/8bb54a48-e136-11e5-8509-e255abc1c8bd.png)
![ff-ok](https://cloud.githubusercontent.com/assets/986182/13492163/c1013824-e136-11e5-9a8f-ec0c6be3a285.png)

**Comment by senshu** [comment]
The presentation editor is based on Chromium, the open-source version of Google Chrome.
Have you checked the font rendering in Chrome?

**Comment by tvld** [comment]
Forgot to mention: yes. Chromium shows ok. Would you like the .svg?

**Comment by senshu** [comment]
Yes, please.

**Comment by tvld** [comment]
[Render-issue.zip](https://github.com/senshu/Sozi/files/160482/Render-issue.zip)

**Comment by senshu** [comment]
I could reproduce the issue in Sozi with your document.
It renders correctly in Firefox and Chromium 48, but not in Sozi, which uses NW.js 0.12, based on Chromium 41.

However, I have never observed this issue in my own presentations, so maybe there is something unusual in your document.

**Comment by tvld** [comment]
well... did nothing special, jst started with a small empty document, some square block, a few lines and some labels )))...  Maybe it is possile to upgrade to NW.js 0.13?  That one uses chromium v47...

**Comment by senshu** [comment]
Unfortunately, the build script for Sozi depends on a tool [that does not support NW.js 0.13 or later](https://github.com/nwjs/nw-builder/issues/300) yet.

The good news is that I have successfully built Sozi using [Electron](http://electron.atom.io/) instead of NW.js. Electron 1.2 is based on Chrome 51, which fixes your font issue.

I will publish a new non-official release soon.

**Comment by tvld** [comment]
Great... in fact we really like Electron... so, looking forward :)

**Comment by senshu** [comment]
The latest build of Sozi is available here: https://drive.google.com/folderview?id=0ByRUreHgekjMWG9teGM2dE8wck0&usp=sharing

It has exactly the same features as Sozi 16.02.
The only difference is the underlying browser engine.
