### ISSUE TITLE
Sozi-16.02.141048-win64 doesn't launch on Windows 10

### ISSUE THREAD

**Issue by Christophe-38** [senshu/Sozi#357]
Hi,
Wanted to try Sozi, work perfectly on windows 7 64 , but close itself intentaneously on windows 10 64.
Best

**Comment by senshu** [comment]
I have published a new non-official version here: https://drive.google.com/folderview?id=0ByRUreHgekjMWG9teGM2dE8wck0&usp=sharing#list

Can you please tell me if it has the same issue?

**Comment by Christophe-38** [comment]
Bonjour,

Je viens de tester rapidement sur un PC Win 10 64 à jour, le logiciel 
s'ouvre parfaitement et ouvre un svg.

Je n'ai pas eu de bug.

Merci pour ce travail, je utilise de plus en plus Sozy pour mes 
présentations et mes élèves aussi.

(Je suis prof en sciences de l'ingénieur)

Bonne soirée

Christophe Guichou
