### ISSUE TITLE
It didn't work on my Windows 10

### ISSUE THREAD

**Issue by elvishsieh** [senshu/Sozi#359]
Hi,
I downloaded Sozi for Windows from Sozi website, however it did not work on my Windows 10 system. So, I git clone the source code to build it and still did not  read the first-presentation.svg yet. My system was Win64 version of Windows 10. Could I miss some thing for running Sozi?

**Comment by senshu** [comment]
> Could I miss some thing for running Sozi?

Yes, I suppose. But I'm afraid I cannot help you if you don't give more details.
The description of your problem is only: "It didn't work". What kind of answer do you expect?

**Comment by elvishsieh** [comment]
Hi Savaton,

Thanks for your reply this issue.

When I run Sozi on Windows 10, then open the  first-presentation.svg on it. It didn't show the menu on right side of Sozi. This was screenshot on the following:
![sozi2](https://cloud.githubusercontent.com/assets/6705295/14586878/585f209e-04d9-11e6-9f4b-7381c60fb8fd.png)
![sozi](https://cloud.githubusercontent.com/assets/6705295/14586882/6271235c-04d9-11e6-86e8-6fa1788f4cea.png)
I wait it for a long time, but it still did not work. I have tried others version on my O.S, e.g. 16.02, 15.11. win32, x64, etc ..., even I tried to build it from source code. It still didn't work yet. I drag and drop  first-presentation.svg into Sozi, and the screenshot on the below:
![sozi3](https://cloud.githubusercontent.com/assets/6705295/14586936/d4578f96-04da-11e6-99f1-4bad3035da53.png)
Maybe I miss some thing for running it?

**Comment by senshu** [comment]
Have you tried to click the button "Load local file" ?

**Comment by elvishsieh** [comment]
Yes, I have tried it.

**Comment by senshu** [comment]
> Yes, I have tried it.

An what did you observe?

**Comment by elvishsieh** [comment]
I wait it for a long time, however nothing was displayed in my monitor. I have draged and dropped .svg file when used the 16.02 x64 version of Sozi. It crashed, so I must press "Ctrl + Alt + Del" to stop this process on Windows.

**Comment by IADDIC** [comment]
pretty much the same exact issue here.  Windows 10.  App just stalls.  I open the app the select "load local file"  which takes me a directory of language files.  I select one and the app returns to the same screen.  Nothing happens...nothing after that.

**Comment by senshu** [comment]
> I open the app the select "load local file" which takes me a directory of language files. I select one

You are supposed to load an SVG file.

**Comment by senshu** [comment]
@elvishsieh Drag and drop is not supported. You are supposed to click the "Load local file button" and select and SVG file.

**Comment by senshu** [comment]
To all. Please understand that my PC does not run Windows 10. I have not tested Sozi on this platform. Without a clear explanation of what you did, what you expected and what you got, I cannot figure out if your problem is a bug or if you just did something wrong.

**Comment by elvishsieh** [comment]
@sunaku Thanks you again. Could I ask you this question which Sozi project have used NW.js to develop it?

@IADDIC If you want to use the Sozi on Windows 10. It had a workaround way, which followed the"[Install Sozi 13 on Windows](http://sozi.baierouge.fr/pages/install-windows.html)" steps to install on Windows 10. Watching [this video](https://www.youtube.com/watch?v=QOuf7w_Qesk) to use it.

**Comment by senshu** [comment]
> Thanks you again

Sorry if this sounds rude but this page is not a help forum for users.
In the issue pages of GitHub, **you** are supposed to help me diagnose issues so that I can fix them.
Currently, you decided to give up without giving useful information about your problem, so I cannot correct it for other users.

> It had a workaround way, which followed the"Install Sozi 13 on Windows"

Sozi 13 is no longer supported. If you plan to use it, be aware that you will get no answer to your questions and bugs will not be fixed.

**Comment by elvishsieh** [comment]
@senshu I very sorry to counter the issue pages of GitHub. I have never given up to use the new version of Sozi, but I have to use the workaround way to create my slide immediately. I will not have more time to track all of the source code of sozi. to help you to fix the bug. Maybe the problem was come from the others javascript projects when used it?

**Comment by senshu** [comment]
I'm closing this issue since I didn't get a clear description of the problem.
Please open another issue if you think it is relevant.

**Comment by elvishsieh** [comment]
It's ok and thank for your help.

elvis hsieh

Guillaume Savaton <notifications@github.com>提到：

>I'mclosingthisissuesinceIdidn'tgetacleardescriptionoftheproblem.Pleaseopenanotherissueifyouthinkitisrelevant.Youarereceivingthisbecauseyouwerementioned.Replytothisemaildirectly,viewitonGitHub,ormutethethread.
