### ISSUE TITLE
Text zones not loaded

### ISSUE THREAD

**Issue by Gabarael** [senshu/Sozi#360]
Hi Senshu,

I just instaled Sozi 16.02 on Windows 7 64bits.

I created a test picture with inkscape 0.91, I included in it drawings and text zones, saved it as a .svg file, and then opened the file with Sozi.

The file loaded, but the text I wrote in inkskape is not shown (wich is a little anoying to perform my presentation).

Except these two bugs, the transitions work well and I can save my file as a .html and play it.

Thanks a lot for your work and support.

**Comment by Moini** [comment]
Gabarael, you need to convert your text to normal text. Flowed text doesn't work anywhere but in Inkscape, see https://inkscape.org/en/learn/faq/#Flowed_text_doesn%27t_show_up_in_exported_file

**Comment by senshu** [comment]
This is also explained in the FAQ of Sozi:
http://sozi.baierouge.fr/pages/faq.html

**Comment by Moini** [comment]
@senshu : could you link to the Inkscape website FAQ from your website? The one in the Wiki isn't updated regularly. The replacement link to use would be: 
https://inkscape.org/en/learn/faq/#Flowed_text_doesn%27t_show_up_in_exported_file

**Comment by senshu** [comment]
@Moini Done. Thanks.
