### ISSUE TITLE
grunt installation failes

### ISSUE THREAD

**Issue by beralt85** [senshu/Sozi#361]
I tried to install the new version of sozi.
running `grunt`, the build stops with

```
Running "compress:osx32" (compress) task
Created build/Sozi-16.05.041153-osx32.zip (37541741 bytes)

Running "compress:linux32" (compress) task
Fatal error: If encoding is specified then the first argument must be a string
```

**Comment by beralt85** [comment]
Downgrading grunt and nodejs helped:

```
downgrading package nodejs (6.0.0-1 => 5.11.0-1)
downgrading package nodejs-grunt-cli (1.2.0-1 => 1.0.0-1)
```

Now it's building.

**Comment by senshu** [comment]
As a temporary fix, I have added the node version requirement to the README.

**Comment by senshu** [comment]
The issue has been fixed in grunt-contrib-compress.
Sozi can be built successfully even with nodejs 7.
