### ISSUE TITLE
Sozi 16 on Wheezy

### ISSUE THREAD

**Issue by MeraX** [senshu/Sozi#367]
Hi,

I am trying to get Sozi running on Debian Wheezy (64 bit). When I try to start the precompiled Sozi from the Sozi-16.02.141048-linux64.tgz package, I get the following error:

```
./Sozi: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./Sozi)
```

That is because Wheezy comes with version 2.13.
Next I tried to compile Sozi on my system. I expected that it would link against the installed glibc version (2.13), but that is not the case. It still expects GLIBC_2.14.

Does any one has any ideas?

EDIT: Okay, after reading https://github.com/senshu/Sozi/issues/309#issuecomment-127559886 there is probably nothing I can do about it from the Sozi side and I rather would have to recompile NW.js, if that is even possible. Is that correct?

**Comment by senshu** [comment]
> I rather would have to recompile NW.js, if that is even possible. Is that correct?

Yes. Even if you build Sozi from source, you will still get the official binary release of NW.js.
I have not tried to rebuild NW.js myself.

**Comment by senshu** [comment]
I have published a new non-official version here: https://drive.google.com/folderview?id=0ByRUreHgekjMWG9teGM2dE8wck0&usp=sharing#list

Can you please tell me if it has the same issue?

**Comment by MeraX** [comment]
Thanks for your effort, but recently I updated to Jessie, so GLIBC_2.14 is available. Unfortunately, I don't have any glibc 2.13 system available to test your new version.

Nevertheless, I build a brilliant presentation with Sozi. Thanks a lot for that!

**Comment by senshu** [comment]
Thanks. Actually, I do not really expect the problem to be solved by the new version. I will try in a VM with Debian 7 when I have time.
