### ISSUE TITLE
Sozi minimizes automaticaly when started

### ISSUE THREAD

**Issue by 304FV** [senshu/Sozi#370]
So, i just installed Sozi 16 on my Windows 10, the first day everything was perfect, but then it just minimized and... thats it.

When trying to open starts, open the file explorer and disappears but without closing the program, Some solution? (Sorry for my English)

**Comment by senshu** [comment]
I have published a new non-official version here:
https://drive.google.com/folderview?id=0ByRUreHgekjMWG9teGM2dE8wck0&usp=sharing#list

Can you please tell me if it has the same issue?

**Comment by tinkyCys** [comment]
Hi, I have the same issue, but I can't test the beta version because I'm on my work computer and Google Drive is blocked so I can't download it.
304FV, Can you tell me if it works ? Thx

**Comment by elvishsieh** [comment]
I have download the new non-official version, which can wok on my Windows 10 x64. It saved as .json file rather then .html file. Therefore, I can't present  my slides with browser. This is my test report for the version.

**Comment by senshu** [comment]
@elvishsieh 

> I have download the new non-official version, which can wok on my Windows 10 x64

According to #359, you didn't have the issue that @304FV reported, so it is not surprising that this version opens correctly for you.

> It saved as .json file rather then .html file. Therefore, I can't present my slides with browser

This is not related to the current bug report. Please open a separate issue for this problem.

**Comment by senshu** [comment]
@elvishsieh

I have fixed the saving issue. Sozi 16.06.221112 should save your presentation to HTML
https://drive.google.com/folderview?id=0ByRUreHgekjMWG9teGM2dE8wck0&usp=sharing#list

**Comment by elvishsieh** [comment]
@senshu 
It's work, thank a lot.

**Comment by senshu** [comment]
According to #357 this issue is fixed.
