### ISSUE TITLE
SOZI 16.02 - Link to open a PDF document

### ISSUE THREAD

**Issue by lagrattecchouette** [senshu/Sozi#371]
Hello,

To create a link to a PDF document INSCKAPE to power in sozi on this type of link "href" placed in an picture open the PDF or other document.
I write well this link as below.

xlink: href = "C: \ Users \ SRZ \ Documents \ Sozi \ Projects \ Presentation1.pdf"

it does not work when I click on it in firefox.
Can anyone help me how to write the way the relationship to make it work in sozi 16.02.

Thank you

**Comment by senshu** [comment]
> xlink: href = "C: \ Users \ SRZ \ Documents \ Sozi \ Projects \ Presentation1.pdf"

You are not supposed to put spaces after ':' and '\'. Did you really write it like this?
Maybe `xlink:href="file://C:\Users\SRZ\Documents\Sozi\Projects\Presentation1.pdf"` would work.

Hyperlinks are a native feature in SVG and Inkscape. Your problem is not related to Sozi and should not be reported here. If you want to ask for help, please use the discussion group at http://groups.google.com/group/sozi-users

**Comment by lagrattecchouette** [comment]
Sorry,
I did not know this part of the code does not concern sozi 16.02.
Thank you for the link.

I finally found the problem is it takes from the directory concerned to
write the link.

for example:
xlink: href = "C: \ Users \ SRZ \ Documents \ Sozi \ Projects \
Presentation1.pdf"

My directory sozi and the project is: Sozi
So it works if I write my code as follows.

xlink: href = "Projects \ Presentation1.pdf"

Thank you

2016-06-06 22:59 GMT+02:00 Guillaume Savaton <notifications@github.com>:

> xlink: href = "C: \ Users \ SRZ \ Documents \ Sozi \ Projects \
> Presentation1.pdf"
>
> You are not supposed to put spaces after ':' and '\'. Did you really write
> it like this?
> Maybe
> xlink:href="file://C:\Users\SRZ\Documents\Sozi\Projects\Presentation1.pdf"
> would work.
>
> Hyperlinks are a native feature in SVG and Inkscape. Your problem is not
> related to Sozi and should not be reported here. If you want to ask for
> help, please use the discussion group at
> http://groups.google.com/group/sozi-users
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/senshu/Sozi/issues/371#issuecomment-224086485>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ASui8C1Vc071uINnYgM6BYa4RxQ9S67Qks5qJIoYgaJpZM4IvCtA>
> .
>



-- 
A+
Santiago

" La musique donne une âme à nos cœurs et des ailes à la pensée." - Platon
