### ISSUE TITLE
Center of rotation of layers

### ISSUE THREAD

**Issue by SteeveDroz** [senshu/Sozi#377]
Feature request: being able to decide the center of rotation of a layer. 

I was trying to rotate an element on screen, for a nice animation and it ended up being a rotation + translation transformation. The thing went all over the place before coming back to its location, rotated. 

There should be an Inkscape-like way to change the center of rotation and allow the user to do what I wanted.

**Comment by senshu** [comment]
Can you please provide an example document that illustrates the issue?

In a Sozi transition, the rotation center is not defined as a fixed point. During a transition, the "camera" follows a path from the center of the origin frame to the center of the destination frame. At each animation step, the center of rotation is the current location of the camera.

If you want to create a transition that is a pure rotation, you must make sure that the origin and destination frames have the same center.

**Comment by SteeveDroz** [comment]
Yep, that's how I understand it. But what if I want to rotate around the origin and then, for a second animation, rotate it around an arbitrary point?

**Comment by senshu** [comment]
> what if I want to rotate around the origin and then, for a second animation, rotate it around an arbitrary point?

Let's consider that we have two frames A and B.
I would create an intermediate frame C between A and B and define the first animation on transition A-C and the second animation on transition C-B.
Setting the timeout of C to 0 will make both animations run in sequence as if it were a single transition.

**Comment by SteeveDroz** [comment]
That is truly amazing, I didn't know that feature! Thanks a lot, you and your software are awsome!
