### ISSUE TITLE
in the documentation for layers, the moon is illuminated on the wrong side.

### ISSUE THREAD

**Issue by richard-delorenzi** [senshu/Sozi#381]
### Summary of your problem or feature request

Sun is on the right, moon is illuminated on the left

### Version of Sozi and other relevant software

web site documentation

### Steps to reproduce the problem

Read documentation on layers

### Expected behavior

Moon should be illuminated , as a half moon on the right.

**Comment by senshu** [comment]
Fixed in last update of the web site.
