### ISSUE TITLE
Installation Instructions: Turn and Face the Strange Ch-ch-changes

### ISSUE THREAD

**Issue by leycec** [senshu/Sozi#382]
The existing [README.md](https://github.com/senshu/Sozi/blob/master/README.md) installation instructions for Debian-based Linux systems (e.g., Ubuntu) would benefit from a few minor revisions. Specifically:

* **`npm` must be explicitly installed.** The current instructions only install Node.js via the `nodejs` package, which fails to install NPM.
* **A symbolic link from `/usr/bin/nodejs` to `/usr/bin/node` must also be explicitly installed,** ideally via the `nodejs-legacy` package. The version of Bower installed by the current stable release of Node.js on most Debian systems (e.g., Ubuntu 16.04) is presumably obsolete, referencing the deprecated `node` binary rather than the modern `nodejs` binary:

        $ bower install
        /usr/bin/env: ‘node’: No such file or directory

* **The optional installation of Wine should be optional.** Currently, Wine is a mandatory rather than optional dependency of Sozi. This is purely balls crazy. I doubt most Linux users require or desire Wine support merely to install Sozi. Your mileage may vary. <sup>_Microsoft gonna Microsoft._</sup>

## What Could Possibly Go Wrong?

The issue with _not_ installing Wine, of course, is that the mandatory `electron` dependency installed via Grunt foolishly requires Wine. Attempting to run `grunt` in the Sozi repository _without_ installing Wine will reliably fail with the following installation error:

```
$ grunt
     .
     .
     .
Packaging app for platform win32 x64 using electron v1.2.0
Warning: Could not find "wine" on your system.

Wine is required to use the app-copyright, app-version, build-version, icon, and 
win32metadata parameters for Windows targets.

Make sure that the "wine" executable is in your PATH.

See https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms for details. Use --force to continue.

Aborted due to warnings.
```

**This is terrible news.** Wine should _not_ be required to install Sozi – but it is.

Likewise, note that attempting to run `npm install` in the Sozi repository _without_ installing the `nodejs-legacy` package will reliably fail with the following installation error:

```
$ npm install
         .
         .
         .
> iltorb@1.0.13 install /home/pietakio/js/Sozi/node_modules/iltorb
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-59-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pietakio/js/Sozi/node_modules/iltorb
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:iltorb@1.0.13 iltorb@1.0.13 install: `node-gyp rebuild`
npm WARN install:iltorb@1.0.13 Exit status 1
```

As the `/bin/sh: 1: node: not found` line implies, the `node-gyp` dependency _also_ appears to require the `/usr/bin/node` symlink. The solution here is simple: **install `nodejs-legacy`,** as above.

## So What're the Changes, Huh?

Pretty minor, all things considered. As your inept volunteer, I advise editing the introductory paragraph of the _Installation_ section to read:

> Install Node.js (< 6.0.0), Bower, the Grunt CLI, and (_under Linux and OS X_) Wine. Yes, Wine is currently a hard dependency of Sozi on non-Windows platforms – even if you don't intend to ever build a Windows executable.

> In Debian-based Linux distributions (e.g., Ubuntu, Mint), run the following commands:

```
sudo apt install nodejs nodejs-legacy npm wine
sudo npm install bower grunt-cli -g
```

## So Where's the Pull Request, Eh?

No pull request, I'm afraid. Time's limited, the video games won't play themselves, and the changes above are trivial. Best of luck and thanks for all the Sozi-fabricated goodness! :sweat_smile:

**Comment by senshu** [comment]
> Wine is currently a hard dependency of Sozi on non-Windows platforms

I have to disagree with this statement. As the current README says:

> If you plan to build a Windows executable from Linux or OS X, also install wine.

Which means that Wine is not required if you don't build for Windows.

Now, the real issue is that the documentation does not explain how to prevent building an executable for Windows.

**Comment by senshu** [comment]
I have update the build instructions.

I have changed the build configuration file format, so please pull the latest changes if you want to try building without installing wine.
