### ISSUE TITLE
Generated html has no functional animations

### ISSUE THREAD

**Issue by fraxinas** [senshu/Sozi#386]
### Summary of your problem or feature request
the generated html output has no animations in it

### Version of Sozi and other relevant software
i had been using sozi since 2011 but so far i'd only worked with the versions that let you define the frames directly inside of Inkscape using a plugin, i've never had any problems with that. 
Version 16.02 of sozi i couldn't get to work at all on my Arch linux system (it would crash right away)
Now i've build Sozi-17.04.071434-linux-x64 from git following the instructions and it seemed to work all right, I can add frames and move and rotate the view around and save the presentation. when I close and load it again in the Sozi program, the frame definitions are restored correctly.

$ uname -a
Linux fox 4.10.6-1-ARCH #1 SMP PREEMPT Mon Mar 27 08:28:22 CEST 2017 x86_64 GNU/Linux

I've tried Chromium 57 and Firefox 52, however the demo presentation (https://github.com/senshu/Sozi/raw/master/samples/first-presentation.sozi.html) works fine
that svg is also the base image that i used for testing.

### Steps to reproduce the problem
I followed the tutorial. My files are here:
http://dreambox.guru/first-presentation.sozi.html
http://dreambox.guru/first-presentation.sozi.json

### Expected behavior
Presentation should start on frame 1 and mouse clicks should advance frames like in the tutorial

### Observed behavior

Only a small overview is shown, with TOC on the right side, no possibility to view single frames or animate between them

**Comment by senshu** [comment]
I have fixed this issue but I forgot to push the changes to the source repository. Now, you can `git pull` and rebuild. Open your presentation again and let the editor save it. Please tell me if it works.

Do you have a specific reason for building Sozi yourself instead of using the [official stable release](https://github.com/senshu/Sozi/releases)?

**Comment by momeni** [comment]
@fraxinas you can install sozi on ArchLinux using [this AUR package](https://aur.archlinux.org/packages/sozi/). Version 17.02-2 includes this fix.

**Comment by fraxinas** [comment]
i actually ended up using the old version 13.11 of sozi again because i simply was so used to doing it inside of Inkscape, i actually found that very convenient. especially having everything in a single file was nice.
i added a few scripts to show/hide/transform layers (groups) on frame change. https://dreambox.guru/prezi/building_a_photobooth.svg
