### ISSUE TITLE
Lithuanian translation

### ISSUE THREAD

**Issue by colideum** [senshu/Sozi#389]
Hi,
This is really great software, maybe a little bit laggy, when more slides/objects are created/added, but overall 10 points.
I translated Lithuanian translation (https://translations.launchpad.net/sozi/15.05/+pots/sozi-15/lt/+translate), so it could be added to Sozi distribution.

One additional feature could be added to have speed up overloaded presentations: possibility to jump from one to another html presentation file.

**Comment by senshu** [comment]
Your translation has been added. It will be available in the preview release Sozi 17.05 at:
https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0?usp=sharing

Thanks for your contribution.
