### ISSUE TITLE
problem in showing slides in v 17.02 sozi

### ISSUE THREAD

**Issue by ghost** [senshu/Sozi#390]
### Summary of your problem or feature request

install sozi from aur, and when i create slides, html created and when i use it nothing happend

### Version of Sozi and other relevant software

* Which version of Sozi are you using? 17.02
* Which drawing software did you use? svg on sozi site!
* On which platform? Arch Linux 64 bit 
* If your problem happens when playing a presentation, which browsers have you tried? Firefox 46 and Chrome 52

### Steps to reproduce the problem

i just go step by step from example in sozi site but nothing happed in html file. i can't found problem. but the frame show in url but nothing move in sildes.

### Expected behavior

we expect that when press space or left click show first slide and so on.

**Comment by mrillusion** [comment]
fix in Sozi 17.02.072116

**Comment by senshu** [comment]
So I assume that we can close this issue. Can you confirm that?
