### ISSUE TITLE
Interface not correctly sown (low part void) on Debian Sid

### ISSUE THREAD

**Issue by claurita** [senshu/Sozi#394]
### Summary of your problem or feature request
On Debian Sid, frame sequence on the low part of the interface is not shown, and often neither the left buttons group to add a new frame (the bottom part of the interface remains void).
When the buttons are shown, the program seams to work (new frames properties are correctly updated, but nothing appears where the frame sequence should be) and the resulting presentation is correct.
May I know the graphic dependencies of the package?
I suspect there could be an issue with some sort of graphic library.

### Version of Sozi and other relevant software
17.02 (latest download)

Thanks in advance
Claudio

**Comment by senshu** [comment]
> May I know the graphic dependencies of the package?

Sozi is an [Electron](https://electron.atom.io/) application. Its UI is HTML rendered inside a browser engine based on Google Chrome.

Does the problem occur with specific SVG documents?
I could imagine that a broken SVG could prevent rendering the rest of the UI.

Please also try the current development version 17.06.021848. You can download it from the [Sozi nightly shared folder](https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0?usp=sharing).

**Comment by claurita** [comment]
Thank you for your answer.
The problem with the nightly build is that in my case sozi must run on a 
32 bit system.
I tried to build it from source, but there is a problem in the 
installation of npm from Debian Sid repos.
I will try again ASAP.

The problem doesn't seem related to a particular SVG. I tried with a 
very simple one box design made with Inkscape and with a very simple map 
made with Vue.
I don't know much about electron, but with the similar tool for Firefox 
it was possible to launch the application directly in the browser (with 
a command line parameter) instead of using the embedded engine.
Is it something possible with electron too?

Anyway, I have Chromium installed (Chrome 32 bit has gone). May be a 
problem?

Claudio

**Comment by senshu** [comment]
> with the similar tool for Firefox it was possible to launch the application directly in the browser [...]. Is it something possible with electron too?

I don't think so.

> Anyway, I have Chromium installed (Chrome 32 bit has gone). May be a problem?

It is unlikely.

If needed, I will upload a 32-bit build of the latest development version. With Sozi 17.06, you can press F12 to show the developer tools and see the error console.

**Comment by claurita** [comment]
Would be great!
Thank you


Il 27/06/2017 13:57, Guillaume Savaton ha scritto:

**Comment by senshu** [comment]
Sozi 17.06 for Linux 32-bit is available from https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0?usp=sharing

**Comment by claurita** [comment]
Perfect!
I tried it both on an (almost fully) updated version of the system (with 
X 1.19) and on an older one (with X 1.16).
Works well.
In the older system, 17.02 had many graphical problems (for example, the 
svg open dialog remained hidden by the main window).

Just a curiosity: have you used a newer version of electron or just a 
new html layout?

Thank you very very much.
Claudio

P.S. I have another problem with the svg generated by vue and modified 
by inkscape, but I'll open a new ticket for that (I need some debugging 
tips for that kind of problems)
Thank you again

**Comment by senshu** [comment]
> Just a curiosity: have you used a newer version of electron or just a new html layout?

Sozi 17.06 uses a recent version of electron. The HTML of the UI has been changed very slightly to be compatible with that version of electron.

**Comment by Antonio-Geremia** [comment]
I think to have a similar issue on Windows 10.
I record a small video to show you better what happens.
https://youtu.be/uV03CJ7FOG0

Thank you.

**Comment by senshu** [comment]
@Antonio-Geremia I see from your video that you are using Sozi 17.02. As explained earlier in this thread, Sozi 17.06 solved the issue for Debian. Can you please try it in Windows 10 and tell me if it works better ?

**Comment by Antonio-Geremia** [comment]
Ok, I didn't realise there was a 17.06 release for windows. I try it and It seem to work fine. I suggest you to change the version in the [home page](http://sozi.baierouge.fr/). Thanks for your work!
