### ISSUE TITLE
Latest release not mentioned on sozi website

### ISSUE THREAD

**Issue by Moini** [senshu/Sozi#397]
http://sozi.baierouge.fr/ does not mention the July release 17.06) on its front page, a short info (with info about changes) would be helpful.

**Comment by senshu** [comment]
Yes. But this issue is related to the [Sozi-website](https://github.com/senshu/Sozi-website) project, not to Sozi itself.

**Comment by Moini** [comment]
Oh, sorry, Guilaume, I didn't know that existed here on gh.

**Comment by senshu** [comment]
> I didn't know that existed here on gh.

Sure :-)
It's not obvious if you are not involved in writing or translating the web site.
