### ISSUE TITLE
Video in Sozi 17.06

### ISSUE THREAD

**Issue by Valiber** [senshu/Sozi#399]
Hello,
In the instructions for embedding video and audio it says:
"Download the Sozi-extras-media-[...].zip from the latest release of Sozi."
Unfortunately there is no such file for Sozi 17.02 or 17.06. Are the files already included in the 17.06 download? Should I use the Sozi-extras-media-[...].zip file from the 16.02 release? 
Thanks again for the fantastic program. 
Best regards,
Yuval

**Comment by senshu** [comment]
> Should I use the Sozi-extras-media-[...].zip file from the 16.02 release?

Yes.
I agree that it is not obvious.

**Comment by Valiber** [comment]
Thanks!

**Comment by senshu** [comment]
The "media" extension is now listed with the other files for the 17.11 release.
