### ISSUE TITLE
Video will not play automatically

### ISSUE THREAD

**Issue by frostad-john** [senshu/Sozi#401]
### Summary of problem

Videos are successfully embedded into .SVG and will play in presentation mode if manually clicked, but the auto-play will not work either using "play automatically in Sozi frame" option or using frame id option.

### Version of Sozi and other relevant software

* Which version of Sozi are you using? 17.02
* Which drawing software did you use? Inkscape 0.91
* On which platform? Windows 7 64-bit
* If your problem happens when playing a presentation, which browsers have you tried? Firefox 56, IE 11

### Steps to reproduce the problem

The problem does not occur when inserting the same video into a new .SVG file with just the video, so I assume there is something in the SVG file that is interfering, but have no idea where to start and it is a large file.

**Comment by frostad-john** [comment]
Update: In trying to troubleshoot and reproduce the error I am now unable to get any video to play automatically, even when inserting just the video into a blank .SVG. See the attached files for an example that does not work. The video should play when entering frame id "vid_in_1" and stop when reaching "vid_out_1".

[VideoInsert.zip](https://github.com/senshu/Sozi/files/1431302/VideoInsert.zip)

**Comment by senshu** [comment]
In your screenshot, the box "Play automatically in Sozi frame" is not checked.
It will not work without if this setting is not enabled.

**Comment by senshu** [comment]
By the way, the MIME type does not match your video file. It should be "video/mp4"

**Comment by senshu** [comment]
@frostad-john Can you please confirm that checking the box "Play automatically in Sozi frame" solves the problem?

**Comment by frostad-john** [comment]
Checking the box "Play automatically in Sozi frame" has no effect. In any case, I assumed that this checkbox was for if you wanted it to play as soon as it is visible in any frame rather than in the frame corresponding to the "entering frame id".

**Comment by frostad-john** [comment]
The default MIME type was "video/ogg" when I first accessed the Sozi extension and the videos played before with this as the MIME type. That was one of the first things I tried when troubleshooting this problem.

**Comment by senshu** [comment]
> I assumed that this checkbox was for if you wanted it to play as soon as it is visible in any frame

Do you think I should clarify this topic in the tutorial? Here is the relevant part of http://sozi.baierouge.fr/pages/tutorial-media.html :

> * Play automatically in Sozi frame: check the box to start playing automatically when a Sozi presentation enters a given frame.
> * Start playing when entering frame (id): the Id of the frame where the media should start playing automatically.
> * Stop playing when entering frame (id): the Id of the frame where the media should stop playing automatically.

**Comment by senshu** [comment]
No update was provided after more than 10 months. Not sure if I'm supposed to do anything more on this topic. I'm closing this issue. Please feel free to reopen it if it is still relevant.
