### ISSUE TITLE
Linux Install not completing

### ISSUE THREAD

**Issue by gmarthews** [senshu/Sozi#402]
Make sure that you have read the [documentation of Sozi](http://sozi.baierouge.fr),
and especially the [installation instructions](http://sozi.baierouge.fr/pages/20-install.html)
and the [frequently asked questions](http://sozi.baierouge.fr/pages/faq.html)
before reporting an issue.
Remember that this is not a place to ask questions.
If you want to get help on Sozi, you can join the [sozi-users discussion group](http://groups.google.com/group/sozi-users).

Describe your problem or propose a new feature in the following sections.
Keep the headings and replace the paragraphs with your own text.

### Summary of your problem or feature request

Followed the instructions, but received the message:

Error in file "/usr/share/applications/evince-previewer.desktop": "" is an invalid MIME type ("" does not contain a subtype)

I checked the files given (same message for evince.desktop as well) and could not find any problem there.

### Version of Sozi and other relevant software

* Which version of Sozi are you using? Sozi-17.06.021848-linux-x64 (2)
* Which drawing software did you use? (examples: Inkscape 0.48, LibreOffice Draw 4.2) n/a
* On which platform? (examples: Windows 7 64-bit, Ubuntu Linux 14.04 32-bit, OS X El Capitan 64-bit)ubuntu gnome 16.04
* If your problem happens when playing a presentation, which browsers have you tried? (examples: Firefox 46, Chrome 52)

### Steps to reproduce the problem

What did you do to make the problem happen?
Give enough details to enable us to reproduce the problem.

cd Sozi-17.06.021848-linux-x64/
cd install/
sudo ./install.sh

If you are proposing a new feature, what steps should the user follow to use it?

### Expected behavior

What results did you expect? error message given above

### Observed behavior

What results did you actually get?

### Hints and solutions (optional)

* If you have taken the time to investigate the problem, tell us what you have found.
* If you have ideas on how to fix the problem, please describe them.

A google search came up with the suggestion that there are two semicolons in the files listed - this was not the case.

**Comment by senshu** [comment]
> Error in file "/usr/share/applications/evince-previewer.desktop": "" is an invalid MIME type ("" does not contain a subtype)
> I checked the files given (same message for evince.desktop as well) and could not find any problem there.

These files are not related to Sozi. This issue is in evince and has been reported here: https://bugzilla.redhat.com/show_bug.cgi?id=1471474

The error message should not prevent Sozi from working (which is the *expected behavior*).
Can you tell me if Sozi works as expected after installation?

**Comment by gmarthews** [comment]
It works, I was distracted by the error.

**Comment by senshu** [comment]
OK. I'm closing this issue.
