### ISSUE TITLE
Feature request: Allow frame to align perfectly with a box in the SVG document

### ISSUE THREAD

**Issue by hauberg** [senshu/Sozi#404]
I currently make my slides using Sozi 13 (the Inkscape extension), but would love to migrate to more recent versions. What prevents me is that I need very precise control over what is shown in individual slides. In the old Inkscape extension I can draw a rectangular box in the SVG document, set its position exactly, and then let a given slide only show what is inside the box. I can't seem to figure out how to do something similar in the current version of Sozi. In the current version I have to use the mouse to zoom in on the region I want to show in a slide, but I cannot do this very precisely.

It would be great if I could select a rectangle in the SVG document and select this to be the exact view of a given slide. Then I could draw suitable rectangles in Inkscape and use these to select a slide view very precisely.

**Comment by senshu** [comment]
Have you tried the [Using layers](http://sozi.baierouge.fr/pages/tutorial-layers.html) tutorial?

**Comment by hauberg** [comment]
Thanks! I have just gone through the tutorial. It's quite different from my inkscape-extension workflow, but I think I can see how I can work with this. I'll try to create a presentation in my usual style with this workflow, and report back if it fails for me.

Thanks a bunch for working on this delightful piece of software, by the way.
