### ISSUE TITLE
Feature request: keyboard shortcuts in the editor

### ISSUE THREAD

**Issue by hauberg** [senshu/Sozi#405]
Hi
It would be great the Sozi editor supported keyboard shortcuts for common operations (if keyboard shortcuts already exist, then I apologize, but I couldn't find them).
For example, it would be great if
  Ctrl-N or Ctrl-+
would create a new slide. Other examples could be
  Ctrl-F: "fit to element"
  Ctrl-Delete: "delete the selected frames"

**Comment by senshu** [comment]
I have implemented the following new keyboard shortcuts:

* Fit to element: Ctrl+E
* Create a new frame: Ctrl+N
* Select all frames: Ctrl+A

Deleting frames was already implemented with the Delete key. It works only if no text field is focused.

I have also added the possibility to change the keyboard shortcuts in the preferences pane.

**Comment by hauberg** [comment]
This is amazing -- this will speed up my slide creation quite a bit!

Thanks so much,
Søren

2018-02-18 16:46 GMT+01:00 Guillaume Savaton <notifications@github.com>:
