### ISSUE TITLE
Windows 10 sozi ne s'execute pas

### ISSUE THREAD

**Issue by didierFR57** [senshu/Sozi#409]
Bonjour,
Sur mon Pc fixe, j'ai la version Linux de sozi qui fonctionne très bien.
Pour l'utiliser sur mon portable x64 windows 10 (version 1703 _ 15063.726), j'ai téléchargé l'archive Sozi-17.11.191151-win32-x64.zip
Après avoir extrait les fichiers, j'ai lancé l'exe Sozi et **rien ne s'affiche**.
J'ai lancé le gestionnaire de tâches et je vois Electron qui tourne en tâche de fond.
J'ai fait un essai avec la version Sozi-17.06.021848-win32-x64.zip, même résultat.
Merci de me dire si j'ai fait une erreur dans l'installation de ce merveilleux logiciel.
Didier

**Comment by senshu** [comment]
Votre problème est peut-être lié à ce bug :
https://github.com/electron/electron/issues/10863

Malheureusement, je n'ai pas de PC sous Windows 10. Je ne peux pas reproduire votre problème.

**Comment by senshu** [comment]
This issue is one year old. The next version of Sozi will be based on a more recent version of electron where the aforementioned issue has been fixed. Please feel free to reopen this issue if it is still relevant.
