### ISSUE TITLE
Change frame focus

### ISSUE THREAD

**Issue by orbisvicis** [senshu/Sozi#41]
While exploring the canvas, double-clicking or otherwise selecting out-of-order frames should change the focus to this new frame so the presentation continues thereon.

A problem exists when one frame is used multiple times.

A solution perhaps exists in the VUE software which allows multiple "paths" through a canvas/frames, ie for different POVs or topics (which is cool and I think sozi should have). Then the best solution would be to pick the path/frame combination to minimize the distance between frame/head.

**Comment by senshu** [comment]
Closing this feature request. From my point of view, this use case can be handled with hyperlinks.
