### ISSUE TITLE
Freeze user interface

### ISSUE THREAD

**Issue by guripreto** [senshu/Sozi#411]
### Summary of your problem or feature request

User interface stop working when originally SVG file is reloaded.

### Version of Sozi and other relevant software

* Which version of Sozi are you using? 17.11
* Which drawing software did you use? Inkscape 0.48
* On which platform? Ubuntu Linux 16.04 64-bit

### Steps to reproduce the problem

What did you do to make the problem happen? change SVG file while user interface is opened.

**Comment by senshu** [comment]
The fix, and a few other changes, will be available in Sozi 12.
You can download it from [Sozi nightly](https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0?usp=sharing) (upload is in progress)
