### ISSUE TITLE
installation mac ???

### ISSUE THREAD

**Issue by choryphee** [senshu/Sozi#413]
Bonjour,

et pardon mais ....
les explications lacunaires m'ont suggéré de télécharger le .ZIP windows  ???...pour mac !
il y a un sous dossier APP et non sozi.app comme expliquer, j'ai mis ce dossier dans mes applications...et maintenant !!! on fait quoi ???
aucune fenêtre de travail ne s'ouvre dans inkscape ou ailleurs , on dirait plutôt une interface html...index.html...qui n'est pas un logiciel de travail ...
un peu d'aide .. ou plus d'explications dans le site pour vous éviter d'y répondre sans cesse j'imagine..
merci !!!!

**Comment by senshu** [comment]
> les explications lacunaires m'ont suggéré de télécharger le .ZIP windows ???...pour mac ! 

[Sur la page officielle](http://sozi.baierouge.fr/pages/20-install-fr.html), je ne vois aucune indication qui irait dans ce sens.
Pouvez-vous m'indiquer où se trouvent les explications dont vous parlez ?

Vous êtes censé suivre le [lien vers la page de téléchargement](https://github.com/senshu/Sozi/releases) et télécharger le fichier qui se termine par "darwin".

**Comment by choryphee** [comment]
Bonjour et merci pour votre réponse aussi rapide .. je me sentais totalement démunie devant votre site ...!

désolée pour le ton abrupte ;-) ...


je n'ai trouvé que cette explication ....http://sozi.baierouge.fr/pages/20-install-fr.html

nulle part de darwin .. sauf dans vos fichiers de téléchargement .. qui n'est ni un .dmg ni un .zip......déroutant sans explication.....

donc je recommence avec ce darwin  .tgz.....

j'espère que cela va marcher votre application me semble très intéressante ....

merci  à vous ....

____________________________________________
Pas envoyé de mon iPhone, j'en ai pas


________________________________

**Comment by choryphee** [comment]
finalement tout marche !!

l'exo aussi .... cela est simple et très efficace....

donc on fait les SVG avec inkscape ...et on les "présente" avec sozi ....si je lis bien entre les lignes ;-)


en tant que communicante, je dois cependant insister sur le fait que vos explications sont vraiment lacunaires ...


cordialement et merci



____________________________________________
Pas envoyé de mon iPhone, j'en ai pas


________________________________

**Comment by senshu** [comment]
> nulle part de darwin .. sauf dans vos fichiers de téléchargement .. qui n'est ni un .dmg ni un .zip......déroutant sans explication.....

Je comprends. En l'occurrence, personne ne s'en est plaint jusqu'à présent. Les statistiques de téléchargement montrent que de nombreux utilisateurs trouvent la version pour OS X sans que je les aide. Alors je ne pensais pas qu'il y avait un problème.

> en tant que communicante, je dois cependant insister sur le fait que vos explications sont vraiment lacunaires

De votre côté, lors de votre prochain rapport de bug, merci de donner un titre plus explicite et de renseigner correctement les rubriques proposées. Cette page n'est pas un forum de discussion ni un endroit pour chercher de l'aide. Elle sert à signaler les dysfonctionnements du logiciel ou à proposer des améliorations : votre travail consiste à décrire *précisément* le problème afin de m'aider à le corriger.

En l'occurrence, je me fiche que vous disiez "bonjour", "cordialement", ou que vous mettiez trois points d'interrogation ou d'exclamation à la fin de chaque phrase. Il aurait suffi d'écrire :

> La documentation n'indique pas clairement quel fichier correspond à la version pour OS X.
> La phrase "Sozi est distribué sous la forme d'une archive zip." donne l'impression qu'il faut télécharger un fichier .zip, mais les seuls disponibles sont pour Windows.

**Comment by senshu** [comment]
J'ai mis à jour les instructions d'installation en français et en anglais.
Si elles vous paraissent suffisantes, je vous invite à fermer ce rapport de bug.
Si vous le souhaitez, je vous invite à signaler les autres lacunes ou erreurs que vous pourrez observer dans la documentation.

**Comment by choryphee** [comment]
je n'ai jamais utilisé de forum, bien chef, je vais le faire de suite

si j'y arrive



____________________________________________
Pas envoyé de mon iPhone, j'en ai pas


________________________________
