### ISSUE TITLE
new future

### ISSUE THREAD

**Issue by Pedroernestorc** [senshu/Sozi#414]
Lorsqu'une présentation est faite, le présentateur ne veut pas rester dépendant d'une séquence de diapositive à diapositive
ou un itinéraire. Il est très important qu'à tout moment, vous puissiez cliquer sur n'importe quelle partie de la toile, soit
avec cadre en route ou non, de sorte que la mise au point et le zoom se déplacent vers le site choisi et ne dépendent pas d'une séquence.
Si vous pouvez avoir Sozi peut avoir cette fonctionnalité, ce sera le meilleur programme de présentation.
Je suggère également que vous reveniez au plugin dans Inkscape, la version 13.11 est excellente et mérite de continuer
en cours de développement, même si vous devez payer pour cela, je vous suggère de valoriser votre travail et de lui en attribuer le prix.
Annuler poe cet excellent travail.

**Comment by senshu** [comment]
> Il est très important qu'à tout moment, vous puissiez cliquer sur n'importe quelle partie de la toile, soit
avec cadre en route ou non, de sorte que la mise au point et le zoom se déplacent vers le site choisi et ne dépendent pas d'une séquence.

Cette fonctionnalité est déjà disponible en utilisant des liens.

> Je suggère également que vous reveniez au plugin dans Inkscape, la version 13.11 est excellente et mérite de continuer

La version 13.11 date de 2013. J'ai déjà expliqué les raisons du changement [lors de la sortie de Sozi 14](http://sozi.baierouge.fr/release-14.10.html) et il n'est pas prévu de revenir en arrière.
Je rappelle que Sozi est un logiciel libre : si quelqu'un est intéressé pour reprendre Sozi 13 et le faire évoluer, je n'y verrai aucun inconvénient.

**Comment by Pedroernestorc** [comment]
Merci beaucoup de m'avoir répondu.
J'ai déjà fait des recherches, et j'ai déjà appris à placer la fonctionnalité à travers des liens dans la version 13.11, merci beaucoup.
Mes questions sont maintenant:
 
1- Il y a une possibilité future que dans la version 17.11 ou supérieure, le
possibilité de navigation non dépendante d'une séquence, comme dans la version 13.11 que vous m'avez expliquée et
ce que je veux dire ci-dessus. (La liberté de faire des présentations serait excellente !!!)
2- Les fichiers générés par SOZI, HTML sont-ils encodés en HTML5 ?

Je vous félicite pour cet excellent travail et ce travail, merci.


J'inclus quelques liens de InkScape v0.92.2 Win x32 avec SOZI v13.11 fait par moi, déjà installé et entièrement fonctionnel pour
qui peut avoir besoin d'eux:

InkScape v0.92.2 Win-x32 + SOZI v13.11  Portable :  		http://www101.zippyshare.com/v/JpjOp2Zm/file.html

InkScape v0.92.2 Win-x32 + SOZI v13.11  Instalacion RAR :	 http://www91.zippyshare.com/v/HIRjHgHT/file.html

**Comment by senshu** [comment]
> Il y a une possibilité future que dans la version 17.11 ou supérieure, le possibilité de navigation non dépendante d'une séquence, comme dans la version 13.11 que vous m'avez expliquée et ce que je veux dire ci-dessus. (La liberté de faire des présentations serait excellente !!!)

Je ne comprends pas votre question. Les liens fonctionnent dans la version 17 de la même manière que dans la version 13.

> Les fichiers générés par SOZI, HTML sont-ils encodés en HTML5 ?

Oui.

**Comment by Pedroernestorc** [comment]
Merci

Ma question est: Faire une présentation seulement avec Sozi 17.11, il y a la possibilité de cliquer ou de sauter à un FRAME spécifique
être capable de faire une présentation non-séquentielle non-linéaire?
