### ISSUE TITLE
Visualize frame flow

### ISSUE THREAD

**Issue by orbisvicis** [senshu/Sozi#42]
Add a new layer, perhaps "Sozi.Flow", dynamically updated each time Sozi is run, containing a path (lines+arrow) detailing the journey through the frames.

In large (50+ frames) presentations scattered throughout an entire canvas, it can be easy to forget the order of the frames.

**Comment by senshu** [comment]
Sozi 13 is no longer developed. I am now closing all issues related to Sozi 13.
Please try Sozi 15 and open a new issue if you think that your problem still deserves to be addressed.
