### ISSUE TITLE
Ubuntu 16.04: Issues with clip selection

### ISSUE THREAD

**Issue by jonatansitter** [senshu/Sozi#420]
Hi there,
I'm running Ubuntu 16.04 with Sozi 18.01 in German and I'm having issues with the "Remove invisible elements".
( js/view/Properties.js:97 js/view/Toolbar.js:82
msgid "Clip"
msgstr "Nicht sichtbare Elemente entfernen")
The selection tool doesn't stay the defined size. On every new frame I have to adjust the size again.

**Comment by senshu** [comment]
In my own tests, in Sozi 18.01, the manual selection of a clipping region does not work at all!
I am working on it.

Please give me a detailed scenario of what you are trying to do, with an example SVG if possible.
I need to reproduce the issue if I want to fix it.

**Comment by senshu** [comment]
You can test Sozi 18.02 from https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0
If it does not fix your problem, then I will need more info.

**Comment by charles-plessy** [comment]
I was affected by the same problem (clipping not working) since `Sozi-17.11.191151` and your updated version `Sozi-18.02-1519574632` solved the problem.  Thank you very much ! (And sorry for not reporting the issue earlier.)
