### ISSUE TITLE
Embed video/audio on a presentation

### ISSUE THREAD

**Issue by Casttiiel** [senshu/Sozi#430]
A group of partners and me are planning to make it possible to embed video and audio on a presentation.

The idea is: on any step, you select on which part of the screen do you want a video and attach it.
This will make the presentation stay on that step as long as the videos is running. 

Also, we will look to create a video from the presentation (with this new feature).

Do you think this "new feature" is very hard to do? Will we find lot of problems?

**Comment by senshu** [comment]
Are you planning to re-use and improve the existing video embedding and video conversion features?

All of these are technically possible, but when a presentation contains a video, converting it to a video will be tricky. You will have to manage two kinds of animations that can occur simultaneously: the movements of the SVG canvas, and the video being played.

**Comment by senshu** [comment]
@Casttiiel I'm closing this issue because it has been open for one year with no update from you. Feel free to reopen it if this topic is still relevant.
