### ISSUE TITLE
Reorder the views

### ISSUE THREAD

**Issue by Hermann12** [senshu/Sozi#432]
How can I reorder the views? I tried to drag&drop view 2 before 1, but it doesn't work.

**Comment by senshu** [comment]
Select the frames to move and click on the tiny arrow buttons on the left or right of the frame title at the destination location.

N.B. As explained in the instructions for submitting issues, this is not the right place to ask questions. Please join the [Sozi community forum](http://sozi.baierouge.fr/community/) if you want to get help.
