### ISSUE TITLE
How to test/debug

### ISSUE THREAD

**Issue by Casttiiel** [senshu/Sozi#433]
Hi, I am trying to get used to the code in order to create an issue I created some weeks ago.

I have installed nodejs, npm , etc. Thanks to the recent update of the package.json I can do npm install without problems. 

Now I want to start modifying/adding some code and see the result. As I have seen on the Internet it can be done using the command npm start. But this gives me an error about missing electron. And with electron installed it gives me a syntax error on the first import of the electron.js:

import {app, BrowserWindow} from "electron";
SyntaxError: Unexpected token import

Also, I have tried to build the project using grunt, and then installinz sozi with the result and openning it just gives me an empty window.

![image](https://user-images.githubusercontent.com/18646763/41066450-20480732-69e2-11e8-90f2-0ef0090a5370.png)

I am missing something? There is some other way to starting "develop" things?

NOTE: I also have tried all this without modifying/adding code and the errors are the same.

Thank you.

**Comment by senshu** [comment]
The error message is related to the "import" keyword not recognized.
You are supposed to build Sozi using the instructions from the [README](https://github.com/senshu/Sozi/blob/master/README.md) file. Have you tried that?

**Comment by Casttiiel** [comment]
Yes, I tried that too. I will specify more:

On the root folder:

grunt
cd dist
cd Sozi....linux-x64
./Sozi

And the window that opens is this:
![image](https://user-images.githubusercontent.com/18646763/41107853-7699fc62-6a73-11e8-9401-285d143f909d.png)

These are the versions (using npm version):

sozi: 18.05.28
npm: 3.5.2
node: 4.2.6

NOTE: I have seen that yesterday someone created and issues similar to mine. (#434)
I have tried to press F12 but nothing happens.

**Comment by RogiVentu** [comment]
Same issue for me, and these are my versions:

Ubuntu: 16.04
sozi: 18.05.28
npm: 4.2.0
node: 7.10.1

**Comment by senshu** [comment]
> I have seen that yesterday someone created and issues similar to mine. (#434)

And issue #427 even before.

**Comment by senshu** [comment]
@RogiVentu I use the same versions as yours. I will try to build Sozi in a VM or a chroot to reproduce the issue.

**Comment by senshu** [comment]
I have just pushed a fix. Please `git pull` and rebuild, and tell me if it works for you.
