### ISSUE TITLE
empty window after start

### ISSUE THREAD

**Issue by glor** [senshu/Sozi#434]
### Summary of your problem or feature request

Following the install instructions for the desktop app the resulting instance seams to be missing something (look at the photo at the bottom). Globally installed. I do have the fonts.

### Version of Sozi and other relevant software
* Most recent version from github (2018-06-07)  
* I don't use it but I have Inkscape 0.92.2 installed and LibreOffice 5.4.6.2
* Arch Linux 64bit (actually it's manjaro but the difference is almost nonexisting)
### Steps to reproduce the problem
> What did you do to make the problem happen?  
run the software
> Give enough details to enable us to reproduce the problem.
I really don't know how. If you have some ideas, i'll help

If you are proposing a new feature, what steps should the user follow to use it?

### Expected behavior
Something useful
### Observed behavior
window after start:
![screenshot_2018-06-07_01-34-39](https://user-images.githubusercontent.com/1354608/41070399-fdc5cf6c-69f2-11e8-8fa2-44e2c12531b2.png)

**Comment by senshu** [comment]
> Most recent version from github (2018-06-07)

I assume that you built it yourself; Which versions of node.js and npm did you use?
Have you tried the official realease 18.04 and did you observe the same issue?

**Comment by senshu** [comment]
From the Sozi window, pressing F12 should open the developer tools.
Are there error messages in the "console" tab?

**Comment by senshu** [comment]
I have pushed a fix for the build issue reported in #427 and #433 
Please tell me if it solves your problem.

**Comment by Casttiiel** [comment]
Now its working, thank you very much
