### ISSUE TITLE
need contron on reload

### ISSUE THREAD

**Issue by lazyalways** [senshu/Sozi#438]
The "auto-reload SVG" option makes it really slow. I think it would be good if it can be controlled by a checkbox or toggle switch. This will give simultaneous editing in Inkscape and reload in sozi.

**Comment by senshu** [comment]
You are proposing a work-around, but I would prefer to solve the real problem: reloading should not be slow. Unfortunately, this bug report does not provide enough details to help me understand and reproduce the problem.

When you opened this issue, you were supposed to answer several questions about your environment (operating system, software versions, etc) and your problem (what you did, what you observed, what you expected). I will close this issue and I propose that you open a new one with the requested information.

Thanks.
