### ISSUE TITLE
PNG Render

### ISSUE THREAD

**Issue by sonejostudios** [senshu/Sozi#440]
### feature request

Is there a possibility to render a Sozi animation in a serie of .png files for further video editing?
This would be absolutely amazing!
Thanks in advance
Vince

### Version of Sozi and other relevant software

Sozi 18.04

**Comment by sonejostudios** [comment]
Hey!
I just figure out, it is possible to render to video, that amazing!! :)
https://github.com/senshu/Sozi-export

The only thing is, sozi-to-video deletes the tmp folder after rendering. The only option is to cancel the rendering to get the .png-files.

Could it be possible to an an commandline option to NOT delete the tmp? or, better, to pass a path where the .png files will be rendered?

Thank you very much!
all the best

vince

**Comment by senshu** [comment]
I have added option `-i` to `sozi-to-video` to export as a sequence of PNG files. In this case, option `-o` specifies the target folder.
This feature is available in [Sozi-export 18.07.30](https://www.npmjs.com/package/sozi-export).

See [commit  903f262 in the Sozi-export repository](https://github.com/senshu/Sozi-export/commit/903f2627d388db4ededdb526b45131cea4436592)

If you have problems with this feature, please [open an issue in the Sozi-export project](https://github.com/senshu/Sozi-export/issues)
