### ISSUE TITLE
need control on auto-reload

### ISSUE THREAD

**Issue by lazyalways** [senshu/Sozi#442]
Thanks for this great program.

### Summary of your problem or feature request
Here I would like to propose a feature in Sozi. A reload button instead of "auto-reload SVG" will be helpful in this context.

Let's say I am editing an SVG file in Inkscape and my Sozi is also opened to see how the output looks. Now sozi is able to reload svg file dynamically while editing and saving due to "auto-reload SVG" option after a certain time interval. This feature makes sozi a bit slow and sometimes corrupt the main file (not sure because of this but happens after several editing).
I would recommend a control on "auto-reload SVG" with a manual reload option.

### Version of Sozi and other relevant software

* Which version of Sozi are you using?
18.01-1516985668

* Which drawing software did you use? (examples: Inkscape 0.48, LibreOffice Draw 4.2)
Inkscape 0.92

* On which platform? (examples: Windows 7 64-bit, Ubuntu Linux 14.04 32-bit, OS X El Capitan 64-bit)
Windows 10

* If your problem happens when playing a presentation, which browsers have you tried? (examples: Firefox 46, Chrome 52)
Firefox 61

### Steps to reproduce the problem

What did you do to make the problem happen?
Give enough details to enable us to reproduce the problem.
Let's make an SVG file with 4-5 layers and you want a full control on each layer in sozi. Each layer contains several designs (lines, circles, polygons etc). Now open the same svg in sozi while opened in Inkscape. Do some work in sozi (frames, animations etc). Now edit in inkscape (some change), save it and look on sozi. Repeat it several times.
Then at some point the svg file will not be loaded properly. 
This was what I found few times and found it because of auto-reload option (not sure!)

If you are proposing a new feature, what steps should the user follow to use it?
A manual control on "auto-reload" may resolve this issue.

I am not sure whether this is an essential modification or not but may help in few cases.

**Comment by senshu** [comment]
This feature has been added to Sozi 18.10, available for testers in the [Sozi nightly shared folder](https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0)
In the preferences, you can select the reload mode between: "automatic", "on focus", and "manual".

**Comment by lazyalways** [comment]
Thank you. Hope this will be helpful to others as well.
