### ISSUE TITLE
Rename frame not possible

### ISSUE THREAD

**Issue by lazyalways** [senshu/Sozi#443]
After creating a new frame with SVG file, renaming is not possible in Sozi 18.10.20 version while in same machine 18.04 is working fine. This is tested in Windows 10 64-bit machine and Chrome 69.

Give enough details to enable us to reproduce the problem.

Run Sozi.exe
Open SVG file
Add a new frame
Try to rename the frame. 
==> Here can't edit the "NewFrame" name.

**Comment by senshu** [comment]
Confirmed. The issue is related to https://github.com/infernojs/inferno/issues/1277

**Comment by senshu** [comment]
This is fixed in Sozi 18.10.28-1540722497.
This version is being uploaded to [the Sozi nightly shared folder](https://drive.google.com/open?id=0ByRUreHgekjMWG9teGM2dE8wck0).
