### ISSUE TITLE
Fonts not displayed in firefox but ok with chromium

### ISSUE THREAD

**Issue by magicvince** [senshu/Sozi#447]
When I launch the presentation in my firefox (60.2 on mint debian stretch), the fonts are not displayed correctly. There's only a default font displaying every text objects. But it's working fine with chromium (70.0)

Tested with stable sozi 18.04 and nightly sozi 18.11.04 (.deb version)

**Comment by senshu** [comment]
Without more details, it looks like a bug in Firefox. Do you have a specific reason for reporting this issue here?

Please read the [FAQ](http://sozi.baierouge.fr/pages/faq.html#some-graphics-do-not-render-correctly-in-sozi) on this topic.

**Comment by magicvince** [comment]
Sorry my late answer, I don't know why I haven't seen the community forum. I'll continue to explore this rendering problem and report it in the forum if I don't find an issue

**Comment by senshu** [comment]
> I'll continue to explore this rendering problem and report it in the forum

OK. We can discuss this issue in the forum and find workarounds.

When I wrote "Do you have a specific reason for reporting this issue here?", I meant that, from my point of view, the [Firefox bug tracker](https://bugzilla.mozilla.org/) could be an appropriate place for reporting this issue.
