### ISSUE TITLE
Problems building Sozi from the sources

### ISSUE THREAD

**Issue by escalope** [senshu/Sozi#450]
I have tried to build Sozi from sources with different images. I always get a bowser dependency issue. I have tried to set dependencies to some particular values, but conflict is not gone. Sozi seems to work anyway, but I am afraid this conflict may trigger future issues. 

The error is triggered while building this dockerfile. 
[dockerfile-result.txt](https://github.com/senshu/Sozi/files/2722884/dockerfle-result.txt)

Steps to reproduce:
1. create a folder
2. Copy this file to the folder
[Dockerfile.txt](https://github.com/senshu/Sozi/files/2722887/Dockerfile.txt)
3. Rename the file to be just "Dockerfile"
4. Run "docker build . -t somename" to see the error messages. This will create the "somename" image.
5. To inspect the container to check how is it "docker run -i -t somename /bin/bash". This will create a container wiht the previous image and then run a terminal within.
6. You can run the Sozi with "xhost +172.17.0.1;docker run --user $UID  -ti --rm -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -w /foo -v `pwd`:/foo somename sozi"

Things to consider (I have myself):
- The dockerfile tries to build the software as root. It can be done under another user, but have not tried yet. Yes. Root. I know it is weird. Some people warn against running as root within the container. It can all be improved to run as another user, but this is a starting point. 
- I have no past experience with bower, so I can't tell if the error message is relevant (Sozi seems to launch anyway)
- I could not find details on preferred distribution for the software, so the Dockerfile maybe wrong. In fact, I was unable to make it work with standard debian (replace the first line in the dockerfile with "FROM debian:stretch", for instance and see what happens when running Sozi). The error in that case has to do with the software not running after the install. I did not wrote the message elsewhere, but it has something to do with a browser not found problem (even installed chrome to prevent it). The problem went away with this node.js specific image I am using now.

**Comment by senshu** [comment]
> I was unable to make it work with standard debian

It seems that Debian Stretch ships an outdated version of Node.js.
npm is not available in the repository, neither as part of package nodejs or as a separate packet.
I recommend installing Node.js from [Nodesource](https://github.com/nodesource/distributions#deb)

**Comment by senshu** [comment]
I have tried in a VM since I am not familiar with Docker yet.
Sozi builds successfully in Debian Stretch with Node.js 8 from Nodesource.

Now, you got an error with bower because there is a problem with the command line that you used.
Instead of `bower install`, you ran `bower install bower.json`.

This means that you are asking to install a package named `bower.json`. For some reason, it does not fail immediately, but it tries to install the first match returned by [the bower search engine](https://bower.io/search/) when you query "bower.json".

NB. bower is now deprecated. I will evaluate the alternatives and I will modify the installation instructions.

**Comment by escalope** [comment]
I have to rebuild the docker file with the nodesource. I located a base docker image based on debian and with nodesource already (https://hub.docker.com/r/nodesource/node/). Will check tomorrow
About the bower command, "bower install" said that bower.json was not found. According to bower doc, "bower install bower.json" installs the files told in "bower.json" and should be equivalent to "bower install". It is recommended when "bower.json" is not found, which was another error I had to deal with.

**Comment by escalope** [comment]
Ooops, yes, you are right. OK. Problem solved. It was not the source dist, but the way the Dockerfile changed the directory. I had been using "cd" with success, but, here, it did not work. Used another way, the WORKDIR primitive, and the "bower install" now works.

**Comment by senshu** [comment]
For your information, commit ad0d2fe877b2e45d08fe76a5b7d271b5acfec67b removes the dependency to Bower.

**Comment by escalope** [comment]
This dockerfile is definitely troublesome :(

I am still trying to build from the sources. No bower problem, but it is hard to get the executable

- In the gruntfile.js, the command "git show -s --format..." uses the %cI format which is not available in the git version of debian:jessie. Hence, it produced weird filenames.  I hacked it to be only "%ct"
- The filenames also in the dist, generate long unnecesary filenames. Again, I changed it to be simpler, just the name of the arch and the OS
- At the end of the grunt process, I invoke the "install.sh" script to finish the procedure. This creates the /opt/sozi folder

With this, it should work, but it does not. When executing, it generates this error (see below). The error was known to me since it appeared when I used your debian packaged files. It only went away when another base image was used. 

At this moment, I have tried all of them: debian: jessie, node:slim, node:8-jessie-slim (nodesource too).

It seems the process concludes and that in /opt/sozi one can find binaries. But, on executing, this error appears. Have you found this kind of error before? it seems specific of electron apps.

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from [object Array]
    at Object.<anonymous> (/opt/sozi/resources/electron.asar/browser/init.js:126:7)
    at Object.<anonymous> (/opt/sozi/resources/electron.asar/browser/init.js:191:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)

**Comment by senshu** [comment]
> In the gruntfile.js, the command "git show -s --format..." uses the %cI format which is not available in the git version of debian:jessie

Is there a specific reason for using Jessie?

> Have you found this kind of error before?

No. As far as I can see, these errors happen when starting electron, before starting Sozi itself.

**Comment by escalope** [comment]
> Is there a specific reason for using Jessie?
Not really. It is just a stable release sufficiently modern. Can try stretch too.
> No. As far as I can see, these errors happen when starting electron, before starting Sozi itself.
Pity. I hoped for some quick fix. Electron is a mystery to me.
