### ISSUE TITLE
embedded video does not remain within the designated position

### ISSUE THREAD

**Issue by escalope** [senshu/Sozi#451]
I have recorded a sample video and reencoded to webm format. I read in one forum post that such formats are more friendly with browsers.
First, the video appears always in gray in inkscape
![image](https://user-images.githubusercontent.com/3056482/50753584-9cdf2a00-1252-11e9-88b1-5339157916e3.png)
Then, in sozi, the video seems out of place and when I pan the screen, the video moves around
![image](https://user-images.githubusercontent.com/3056482/50753651-dadc4e00-1252-11e9-8663-747a1eb6d505.png)

The files are attached (svg+video)
[files.zip](https://github.com/senshu/Sozi/files/2731691/files.zip)

I have saved again the svg as a **plain svg** and the bug is gone, so it must be something related with the default inkscape svg format.

I am using the docker container for this (inkscape 0.92 + sozi 18.04)

https://hub.docker.com/r/escalope/inkscape-sozi

**Comment by senshu** [comment]
Checking your document in Inkscape, I see that the video is not part of the "posterbolotweet" layer.
You have two options here:

1. Modify your document to move the video to the layer (recommended).
2. Or keep your document as is, and in Sozi, select the "Default" layer when you want to move the video.
