### ISSUE TITLE
image in an svg file does not show up in the sozi output

### ISSUE THREAD

**Issue by myrmoteras** [senshu/Sozi#452]
we modified a SVG file in inkscape by copying an image into it. We saved as SVG and opened it in Sozi

![image](https://user-images.githubusercontent.com/4609956/51687161-46177580-1ff2-11e9-83fd-07061099b781.png)

we then saved the presentation and the image does not show up in the html output (sozi presentation)

![image](https://user-images.githubusercontent.com/4609956/51687340-98589680-1ff2-11e9-9311-0b0de56bc445.png)

[plazi_workflow_3_bm.sozi.zip](https://github.com/senshu/Sozi/files/2792269/plazi_workflow_3_bm.sozi.zip)

**Comment by senshu** [comment]
@myrmoteras Have you tried this suggestion?

> As a workaround, I would advise you to create the main SVG document with Inkscape, in which you will import the SVG output from Visio and the image.
> Please tell me if it works better.

**Comment by senshu** [comment]
@myrmoteras Any news on this issue?

**Comment by senshu** [comment]
@myrmoteras I'm closing this issue after 10 months without any update from you. Please feel free to reopen it if you think it still deserves my attention.
