### ISSUE TITLE
If you have more than 9 slides, indentation looks deeper than it is

### ISSUE THREAD

**Issue by Moini** [senshu/Sozi#460]
### Summary of your problem or feature request

![screenshot_2019-09-14_12-33-37](https://user-images.githubusercontent.com/3240233/64906903-36b57b80-d6ec-11e9-8f60-b3680e2ccc8e.png)

When the numbers get longer, it looks like an additional indentation level.
This could be fixed by either reserving some more space for the numbers or by using a column / table layout.

### Version of Sozi and other relevant software

* 19.04.22-1555944973 (this could be made easier by not using a notification where I cannot copy paste the version number from!)
* Which drawing software did you use? - Inkscape, but irrelevant for this issue.
* On which platform? Linux Mint 19.2 
* If your problem happens when playing a presentation, which browsers have you tried? FF 69, Chromium

### Steps to reproduce the problem

Create a presentation.
Use more than 9 items in the same indentation level.

### Expected behavior

Indentation looks correct.

### Observed behavior

Indentation looks incorrect.

### Hints and solutions (optional)

see above.

**Comment by senshu** [comment]
> This could be fixed by either reserving some more space for the numbers or by using a column / table layout.

The easiest solution was to use an HTML ordered list as before, but without the tricks that I used to solve a few other issues. I had to remove the "ellipsis" for long frame titles that overflow.
I will upload an intermediate release with this fix soon.

**Comment by senshu** [comment]
You can try Sozi 19.09 (64-bit only) from https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0

**Comment by Moini** [comment]
Thank you, Guillaume, that was very fast!
