### ISSUE TITLE
Size error in audio elements

### ISSUE THREAD

**Issue by 00sapo** [senshu/Sozi#465]
When creating audio elements with controls through Sozi extra, a rectangle with the given size is created. The internal audio element doesn't follow that rule and is shown bigger than the rectangle in firefox and chrome. 
[ismir_slides.zip](https://github.com/senshu/Sozi/files/3763331/ismir_slides.zip)
Using Inkscape 0.94 and Sozi 19 on Manjaro Linux.

**Comment by 00sapo** [comment]
Fixed by adding a `svg:style` tag with the Inkscape xml editor as explained [here](http://tavmjong.free.fr/INKSCAPE/MANUAL/html/Web-Style.html)
The css I used was the following (it forces the internal audio tag to the wanted size):
```css
audio {
	width: 100px;
	height: 25px;
}
```

**Comment by senshu** [comment]
Thanks for reporting the issue.
You solution assumes that all audio elements in a document have the same size.

Another solution is to add a `style` attribute to each `audio` element. I will modify the Inkscape extension to do that.

**Comment by senshu** [comment]
A fix will be available in the next release of Sozi.
I will upload an intermediate version for testers soon.
