### ISSUE TITLE
External Links with target="_blank" or show="new" are opened in the main (presenter console) window

### ISSUE THREAD

**Issue by MerlinZero** [senshu/Sozi#469]
Thank you for the presenter console! It was a major feature missing until now and I appreciate it.

### Summary of your problem or feature request

An object in the svg can have a defined external href (e.g. a HTTP website address) with _target_ set to "_blank" or _show_ set to "new". Using the new sozi presenter html file and clicking the object during the presentation results in the link opening in a new tab **in the main window** (where the presenter console is) instead of the presentation window. So the audience can not see the new content.

### Version of Sozi and other relevant software

* Sozi 20.01.01-1577900785
* Inkscape 0.92
* Windows 7 64-bit
* Firefox 71.0 64-bit

### Steps to reproduce the problem

1. Define a href for an SVG object in Inkscape
(see http://tavmjong.free.fr/INKSCAPE/MANUAL/html/Web-Links.html)
2. Set the _target_ to "_blank" or _show_ to "new"
3. Click on the object during the presentation (inside the presentation window)

### Expected behavior

The link should open in a new tab in the presentation window.

### Observed behavior

The link opens in a new tab in the main window (where the presenter console is).

Without _target_ or _show_ set, the link opens as expected in the presentation window, replacing the presentation. And as expected, the presenter console can then not change/control the presentation (e.g. next slide) until the presentation window has returned to the presentation address (pressing backspace inside the window, the history-back-button is not shown in the minimalistic presentation window).

### Hints and solutions (optional)

If Ctrl+T (for opening a new tab) is pressed inside the presentation window, the new tab is opened also in the main window (presenter console), so the kind of presentation window is causing the problem.

If I'm right, it's because of the way the presentation window is opened in the javascript (its options).
`presWindow=window.open(iframes[0].src,"sozi-presentation","width=600, height=400, scrollbars=yes")`

**If the option `toolbar=yes` is added to window.open, the presentation window has a toolbar (with history-back-button, nice for links without _target_ or _show_) and links are correctly opened in the presentation window.**

I get why the window is opening without the toolbar, but in my use case the presentation window is always switched to Fullscreen with F11, after moving it to the second screen. So the toolbar isn't visible anyway.

The problem could be solved by simply enabling the toolbar. Or by automatically checking if the svg contains objects with href and _target_ or _show_ set - and setting the option in the javascript code accordingly. Or by giving the user a checkbox in the sozi options.

**Comment by senshu** [comment]
Thanks for reporting this issue.

The presenter console has not been designed to handle hyperlinks. I even find it surprising that links without `target` work as expected :)

> The problem could be solved by simply enabling the toolbar.

As long as we can put the presentation window to full screen mode, I agree that enabling the toolbar is an acceptable solution.

**Comment by senshu** [comment]
As far as I could see, links without "target" or "show" did not work either.
Enabling the toolbar was a partial solution, but not sufficient.

Commit 6af97ea is more general: it forwards clicks on hyperlinks from the presenter console to the main presentation window. I will upload a new version soon and you will be able to test it with your use case.
