### ISSUE TITLE
Ctrl-S delete the content in textbox

### ISSUE THREAD

**Issue by GongSiqiu** [senshu/Sozi#472]
### Ctrl-S delete the content in textbox

After editing the content in textbox, such as note, path id and so on, pressing Ctrl-S to save without clicking other place will cancel what I have edited.

### Version of Sozi and other relevant software

* Sozi 20.01.01-1577900785
* debian 10 64-bit

### Steps to reproduce the problem

1. Edit the content in textbox(don't move the focus)
2. Ctrl-S

### Expected behavior

Save my change

### Observed behavior

Cancel my change

**Comment by senshu** [comment]
Thanks for reporting this issue.
This is fixed in the source repository. I will upload a new release soon.
