### ISSUE TITLE
Resizing presenternotes-windows

### ISSUE THREAD

**Issue by ejvindh** [senshu/Sozi#473]
@Sozi20.01:

I can confirm that two of the issues mentioned in [Link](https://github.com/senshu/Sozi/issues/211#issuecomment-569292352) are now fixed: It works in Chromiumbased browsers, and instructions for presenterview-formatting now pops up. Thank you very much :+1: 

In order to be really functional in live sessions, I do however, still believe that the "current view" becomes too small on the presenter screen. I've previously ([link](https://github.com/senshu/Sozi/issues/211#issuecomment-486391307), suggested solution [link](https://github.com/senshu/Sozi/issues/211#issuecomment-486816698)) suggested that they become resizable through the "resize"-tag in css. The reason why I believe this solution to be superior is that it makes it possible for the presenter to adapt to his or her given hardware -- together with his or her preferences as to how many notes that are needed.

It's of course your choice :)

**Comment by senshu** [comment]
Thanks for pointing me to the `resize` CSS property.
Unfortunately, I could not make it work with the current presenter HTML.

As a last resort, I can use the same type of resizing bars as in the editor.

**Comment by ejvindh** [comment]
Attached a suggestion as to how it could be done. As previously mentioned, CSS is not where I excel, so don't be too puzzled if there are details that don't make sense. But the zip-file should show how one could come from the current code to a code in which resize helps the user fit the pages according to his or her own choosings.

The files in the main folder are created by Sozi. The "Test-presenter.sozi.html" file in the subfolder is revised to bring in the blessings of the resize-property. :)
[Test.zip](https://github.com/senshu/Sozi/files/4143817/Test.zip)

**Comment by senshu** [comment]
OK. It seems that `resize` has no effect when the `overflow` property is not specified for some elements.

My preference goes to an horizontal resizer between the left and right parts of the screen, and a vertical resizer between the top and bottom preview areas.
See commit 838475307ede4c512d4c25008f730e230d9c6534

I will upload a new preview release soon.

**Comment by ejvindh** [comment]
Superb, @senshu !!! This is really good.
I have no further quarrels with the current solution :)
Thanks for your great work on this tool.
