### ISSUE TITLE
Show hidden objects only when a viewing a specific slide/frame

### ISSUE THREAD

**Issue by sjn** [senshu/Sozi#57]
Hi! Thanks for making a very useful piece of software!

Is there a way to hide objects that aren't related to the "current view"? Here's my use case:

I have a presentation with text in it, and I would like to take a closer look at different parts of the text throughout the presentation. When I focus at one part (e.g. a paragraph, or a specific quote somewhere) I would like that some supporting objects are revealed, e.g. some arrows and comments, or a rectangle placed behind the text to attract attention to it. I would also like that these supporting objects are otherwise hidden when I view at another part of the text _even if the other view location overlaps the first view_.

Is this something that can be emulated? (e.g. adding an event handler that changes visibility of some objects when the presentation starts, and then subsequently shows and then hides different objects as the presentation proceeds from one frame to the next...)

If this can be done with adding an event handler, I'd be happy with that, but my Javascript skills are quite limited, so an example would be very much appreciated. :)

**Comment by maronin** [comment]
It seems that 

``sozi.events.listen(&quot;framechange&quot;, function (index) { 

``

**Comment by senshu** [comment]
@maronin There is an up-to-date example here: https://github.com/senshu/Sozi/blob/master/samples/show-hide-objects.svg
The correct way to setup the event listener is:

```javascript
sozi.events.listen("sozi.player.framechange", function (index) {...});
```

**Comment by maronin** [comment]
Thank you that works!

**Comment by senshu** [comment]
In Sozi 15, layer opacity allows to achieve a similar effect as showing/hiding objects.
Please try Sozi 15 and open a new issue if you think that your problem still deserves to be addressed.
