### ISSUE TITLE
Add some video_extra examples 

### ISSUE THREAD

**Issue by tfer** [senshu/Sozi#63]
I've seen a youtube demonstration of the add_video feature, but I've been unable to use this feature in any of the OS/browser(s) I've been using, i.e. Windows7/Firefox,Chrome,Opera.  The example is on a linux system, if I had an example sozi file with the played video file, I might be able to figure out what I need to get it working.
[
documentation
]

**Comment by senshu** [comment]
An example has been added to the official documentation at http://sozi.baierouge.fr/pages/tutorial-media.html
