### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by bouteill** [senshu/Sozi#71]
My system: windows 7 - 64 bits.

I followed rigourously all instructions (even selected the old 32bits versions for python, inkscape and pygtk distributions that were recommended). 
However, when selecting SOZI in the extensions menu from InkScape, I still get the following error:

```
 Traceback (most recent call last):

File "sozi.py", line 31, in <module>

import gtk

File "C:\Program Files (x86)\Inkscape\python\lib\site-packages\gtk-2.0\gtk\__init__.py", line 40, in <module>

from gtk import _gtk

 ImportError: DLL load failed: The specified procedure could not be found.
```

I tried this installation on 2 systems (both win 7 64 bits), same error... Help please!!! Would love to try SOZI....
Thanks!

**Comment by thesmyler** [comment]
Hi @senshu this is the exact problem i told you on twitter, did you receive the screen shot I gave you? I am using windows 8, I wonder if it has anything to do with the systems? I think it's here I am confused whilst people like me are using win64 the instructions are to use win32? 

Thank you for your time and help

Denise

**Comment by thesmyler** [comment]
@joweiser your computer, did you do the installations on a mac, windows or linux? are you using win 64 or win32?
