### ISSUE TITLE
Control panel on other web client, via server-push

### ISSUE THREAD

**Issue by F-Hauri** [senshu/Sozi#76]
I've created a "rendez-vous server" that let you dynamically control your slideshow from a third web browser.
You can take a look at http://realtime.f-hauri.ch/slideshow/soziNph-anim.svg
and his control pannel at http://realtime.f-hauri.ch/cgi-bin/command-soziNph.cgi
To try them:
 . First open two web browser windows
 . Past both url into windows, cgi window will show a field and svg will popup a handler
 . Copy the handler from svg's popup to field in cgi window
 . submit the handler in cgi and validate the popup in svg
 . You can now control your svg window from the cgi control panel

**Comment by senshu** [comment]
Is this feature still developed? I will close this thread since it does not report an issue with Sozi itself.
I would suggest to create a separate project for this work and make an announcement to the [sozi-users discussion group](http://groups.google.com/group/sozi-users).
